// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>vMR.Model</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace vMR.Model {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
	using HeD.Model;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsinput:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsinput:r2", IsNullable=false)]
    public partial class CDSInput {
        
        private List<CodedIdentifier> templateIdField;
        
        private List<CDSResource> cdsResourceField;
        
        private VMR vmrInputField;
        
        private CDSContext cdsContextField;
        
        public CDSInput() {
            this.cdsContextField = new CDSContext();
            this.vmrInputField = new VMR();
            this.cdsResourceField = new List<CDSResource>();
            this.templateIdField = new List<CodedIdentifier>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("templateId", Order=0)]
        public List<CodedIdentifier> templateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("cdsResource", Order=1)]
        public List<CDSResource> cdsResource {
            get {
                return this.cdsResourceField;
            }
            set {
                this.cdsResourceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public VMR vmrInput {
            get {
                return this.vmrInputField;
            }
            set {
                this.vmrInputField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CDSContext cdsContext {
            get {
                return this.cdsContextField;
            }
            set {
                this.cdsContextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsinput:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsinput:r2", IsNullable=true)]
    public partial class CDSResource {
        
        private List<CodedIdentifier> templateIdField;
        
        private CD cdsResourceTypeField;
        
        private object resourceContentsField;
        
        public CDSResource() {
            this.templateIdField = new List<CodedIdentifier>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("templateId", Order=0)]
        public List<CodedIdentifier> templateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CD cdsResourceType {
            get {
                return this.cdsResourceTypeField;
            }
            set {
                this.cdsResourceTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object resourceContents {
            get {
                return this.resourceContentsField;
            }
            set {
                this.resourceContentsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsinput:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsinput:r2", IsNullable=true)]
    public partial class CDSContext {
        
        private List<CodedIdentifier> templateIdField;
        
        private Organization cdsInitiatingOrganizationField;
        
        private Person cdsInitiatingPersonField;
        
        private CD cdsSystemUserTypeField;
        
        private CD cdsSystemUserPreferredLanguageField;
        
        private CD cdsSystemUserTaskContextField;
        
        private Organization cdsReceivingOrganizationField;
        
        private Person cdsReceivingPersonField;
        
        private CD cdsInformationRecipientTypeField;
        
        private CD cdsInformationRecipientPreferredLanguageField;
        
        private CD cdsEncounterTypeField;
        
        private CD cdsSubTopicField;
        
        private List<NameValuePair> extensionField;
        
        public CDSContext() {
            this.extensionField = new List<NameValuePair>();
            this.templateIdField = new List<CodedIdentifier>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("templateId", Order=0)]
        public List<CodedIdentifier> templateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Organization cdsInitiatingOrganization {
            get {
                return this.cdsInitiatingOrganizationField;
            }
            set {
                this.cdsInitiatingOrganizationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Person cdsInitiatingPerson {
            get {
                return this.cdsInitiatingPersonField;
            }
            set {
                this.cdsInitiatingPersonField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CD cdsSystemUserType {
            get {
                return this.cdsSystemUserTypeField;
            }
            set {
                this.cdsSystemUserTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public CD cdsSystemUserPreferredLanguage {
            get {
                return this.cdsSystemUserPreferredLanguageField;
            }
            set {
                this.cdsSystemUserPreferredLanguageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CD cdsSystemUserTaskContext {
            get {
                return this.cdsSystemUserTaskContextField;
            }
            set {
                this.cdsSystemUserTaskContextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Organization cdsReceivingOrganization {
            get {
                return this.cdsReceivingOrganizationField;
            }
            set {
                this.cdsReceivingOrganizationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Person cdsReceivingPerson {
            get {
                return this.cdsReceivingPersonField;
            }
            set {
                this.cdsReceivingPersonField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public CD cdsInformationRecipientType {
            get {
                return this.cdsInformationRecipientTypeField;
            }
            set {
                this.cdsInformationRecipientTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public CD cdsInformationRecipientPreferredLanguage {
            get {
                return this.cdsInformationRecipientPreferredLanguageField;
            }
            set {
                this.cdsInformationRecipientPreferredLanguageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public CD cdsEncounterType {
            get {
                return this.cdsEncounterTypeField;
            }
            set {
                this.cdsEncounterTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public CD cdsSubTopic {
            get {
                return this.cdsSubTopicField;
            }
            set {
                this.cdsSubTopicField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("extension", Order=12)]
        public List<NameValuePair> extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
}
