// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>vMR.Model</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace vMR.Model {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsoutput:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsoutput:r2", IsNullable=false)]
    public partial class CDSOutputAsDataType : CDSOutput {
        
        private Value valueField;
        
        public CDSOutputAsDataType() {
            this.valueField = new Value();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Value value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CDSOutput", Namespace="urn:hl7-org:cdsoutput:r2")]
    [System.Xml.Serialization.XmlRootAttribute("CDSOutput", Namespace="urn:hl7-org:cdsoutput:r2", IsNullable=true)]
    public abstract partial class CDSOutput1 {
        
        private List<CodedIdentifier> templateIdField;
        
        public CDSOutput1() {
            this.templateIdField = new List<CodedIdentifier>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("templateId", Order=0)]
        public List<CodedIdentifier> templateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CDSOutputAsVMR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CDSOutputAsStringNameValuePairs))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CDSOutputAsDataType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsoutput:r2")]
    public abstract partial class CDSOutput {
        
        private List<CodedIdentifier> templateIdField;
        
        public CDSOutput() {
            this.templateIdField = new List<CodedIdentifier>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("templateId", Order=0)]
        public List<CodedIdentifier> templateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsoutput:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsoutput:r2", IsNullable=false)]
    public partial class CDSOutputAsVMR : CDSOutput {
        
        private VMR vmrOutputField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VMR vmrOutput {
            get {
                return this.vmrOutputField;
            }
            set {
                this.vmrOutputField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsoutput:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsoutput:r2", IsNullable=false)]
    public partial class CDSOutputAsStringNameValuePairs : CDSOutput {
        
        private List<StringNameValuePair> stringNameValuePairField;
        
        public CDSOutputAsStringNameValuePairs() {
            this.stringNameValuePairField = new List<StringNameValuePair>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("stringNameValuePair", Order=0)]
        public List<StringNameValuePair> stringNameValuePair {
            get {
                return this.stringNameValuePairField;
            }
            set {
                this.stringNameValuePairField = value;
            }
        }
    }
}
