// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Allscripts.Model</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Allscripts.Model {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class VitalSignObservation {
        
        private List<CodedValueType> iDsField;
        
        private List<CodedValueType> codesField;
        
        private VitalSignType vitalSignField;
        
        private string statusField;
        
        private string commentTextField;
        
        private System.DateTime resultDateTimeField;
        
        private string valueField;
        
        private VitalSignUnit unitsField;
        
        private string unitModifierField;
        
        private string interpretationField;
        
        private string referenceRangeField;
        
        private CodedValueType providerIDField;
        
        private CodedValueType encounterIDField;
        
        public VitalSignObservation() {
            this.encounterIDField = new CodedValueType();
            this.providerIDField = new CodedValueType();
            this.codesField = new List<CodedValueType>();
            this.iDsField = new List<CodedValueType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("IDs", Order=0)]
        public List<CodedValueType> IDs {
            get {
                return this.iDsField;
            }
            set {
                this.iDsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Codes", Order=1)]
        public List<CodedValueType> Codes {
            get {
                return this.codesField;
            }
            set {
                this.codesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public VitalSignType VitalSign {
            get {
                return this.vitalSignField;
            }
            set {
                this.vitalSignField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CommentText {
            get {
                return this.commentTextField;
            }
            set {
                this.commentTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime ResultDateTime {
            get {
                return this.resultDateTimeField;
            }
            set {
                this.resultDateTimeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public VitalSignUnit Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UnitModifier {
            get {
                return this.unitModifierField;
            }
            set {
                this.unitModifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Interpretation {
            get {
                return this.interpretationField;
            }
            set {
                this.interpretationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ReferenceRange {
            get {
                return this.referenceRangeField;
            }
            set {
                this.referenceRangeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public CodedValueType ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public CodedValueType EncounterID {
            get {
                return this.encounterIDField;
            }
            set {
                this.encounterIDField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProblemItemBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FamilyHistory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SocialHistory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Problem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Encounter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Procedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Medication))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LabOrder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Allergy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlanOfCare))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Immunization))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public abstract partial class ClinicalItemBase {
        
        private List<CodedValueType> iDsField;
        
        private List<CodedValueType> codesField;
        
        private ClinicalItemStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string commentTextField;
        
        private string searchTextField;
        
        private CodedValueType encounterIDField;
        
        public ClinicalItemBase() {
            this.codesField = new List<CodedValueType>();
            this.iDsField = new List<CodedValueType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("IDs", Order=0)]
        public List<CodedValueType> IDs {
            get {
                return this.iDsField;
            }
            set {
                this.iDsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Codes", Order=1)]
        public List<CodedValueType> Codes {
            get {
                return this.codesField;
            }
            set {
                this.codesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ClinicalItemStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CommentText {
            get {
                return this.commentTextField;
            }
            set {
                this.commentTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SearchText {
            get {
                return this.searchTextField;
            }
            set {
                this.searchTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CodedValueType EncounterID {
            get {
                return this.encounterIDField;
            }
            set {
                this.encounterIDField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FamilyHistory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SocialHistory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Problem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public abstract partial class ProblemItemBase : ClinicalItemBase {
        
        private System.DateTime problemDateField;
        
        private bool problemDateFieldSpecified;
        
        private ProblemType problemTypeField;
        
        private string problemTextField;
        
        private System.DateTime resolvedDateField;
        
        private bool resolvedDateFieldSpecified;
        
        private CodedValueType treatingProviderIDField;
        
        private bool deniedField;
        
        private bool deniedFieldSpecified;
        
        private string categoryField;
        
        private string severityField;
        
        private string clinicalProgressField;
        
        private string lateralityField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime ProblemDate {
            get {
                return this.problemDateField;
            }
            set {
                this.problemDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProblemDateSpecified {
            get {
                return this.problemDateFieldSpecified;
            }
            set {
                this.problemDateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ProblemType ProblemType {
            get {
                return this.problemTypeField;
            }
            set {
                this.problemTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProblemText {
            get {
                return this.problemTextField;
            }
            set {
                this.problemTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ResolvedDate {
            get {
                return this.resolvedDateField;
            }
            set {
                this.resolvedDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResolvedDateSpecified {
            get {
                return this.resolvedDateFieldSpecified;
            }
            set {
                this.resolvedDateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public CodedValueType TreatingProviderID {
            get {
                return this.treatingProviderIDField;
            }
            set {
                this.treatingProviderIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Denied {
            get {
                return this.deniedField;
            }
            set {
                this.deniedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeniedSpecified {
            get {
                return this.deniedFieldSpecified;
            }
            set {
                this.deniedFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ClinicalProgress {
            get {
                return this.clinicalProgressField;
            }
            set {
                this.clinicalProgressField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Laterality {
            get {
                return this.lateralityField;
            }
            set {
                this.lateralityField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class FamilyHistory : ProblemItemBase {
        
        private CodedValueType familyMemberIDField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CodedValueType FamilyMemberID {
            get {
                return this.familyMemberIDField;
            }
            set {
                this.familyMemberIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class SocialHistory : ProblemItemBase {
        
        private SocialHistoryType socialHistoryTypeField;
        
        private bool socialHistoryTypeFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SocialHistoryType SocialHistoryType {
            get {
                return this.socialHistoryTypeField;
            }
            set {
                this.socialHistoryTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SocialHistoryTypeSpecified {
            get {
                return this.socialHistoryTypeFieldSpecified;
            }
            set {
                this.socialHistoryTypeFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class Problem : ProblemItemBase {
        
        private bool wasOneCauseOfDeathField;
        
        private bool wasOneCauseOfDeathFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool WasOneCauseOfDeath {
            get {
                return this.wasOneCauseOfDeathField;
            }
            set {
                this.wasOneCauseOfDeathField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WasOneCauseOfDeathSpecified {
            get {
                return this.wasOneCauseOfDeathFieldSpecified;
            }
            set {
                this.wasOneCauseOfDeathFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class Encounter : ClinicalItemBase {
        
        private string encounterTextField;
        
        private System.DateTime encounterDateField;
        
        private bool encounterDateFieldSpecified;
        
        private CodedValueType providerIDField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EncounterText {
            get {
                return this.encounterTextField;
            }
            set {
                this.encounterTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime EncounterDate {
            get {
                return this.encounterDateField;
            }
            set {
                this.encounterDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EncounterDateSpecified {
            get {
                return this.encounterDateFieldSpecified;
            }
            set {
                this.encounterDateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CodedValueType ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class Procedure : ClinicalItemBase {
        
        private string procedureTextField;
        
        private System.DateTime procedureDateField;
        
        private bool procedureDateFieldSpecified;
        
        private CodedValueType procedureProviderField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProcedureText {
            get {
                return this.procedureTextField;
            }
            set {
                this.procedureTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ProcedureDate {
            get {
                return this.procedureDateField;
            }
            set {
                this.procedureDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcedureDateSpecified {
            get {
                return this.procedureDateFieldSpecified;
            }
            set {
                this.procedureDateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CodedValueType ProcedureProvider {
            get {
                return this.procedureProviderField;
            }
            set {
                this.procedureProviderField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class Medication : ClinicalItemBase {
        
        private bool administeredField;
        
        private string freeTextSIGField;
        
        private System.DateTime startDateTimeField;
        
        private bool startDateTimeFieldSpecified;
        
        private System.DateTime stopDateTimeField;
        
        private bool stopDateTimeFieldSpecified;
        
        private string adminTimingField;
        
        private string frequencyField;
        
        private string intervalField;
        
        private string durationField;
        
        private Route routeField;
        
        private bool routeFieldSpecified;
        
        private string doseField;
        
        private string doseUnitsField;
        
        private string siteField;
        
        private string doseRestrictionField;
        
        private ProductForm productFormField;
        
        private bool productFormFieldSpecified;
        
        private string deliveryMethodField;
        
        private string productNameField;
        
        private string brandNameField;
        
        private string drugManufacturerField;
        
        private string productConcentrationField;
        
        private MedicationKind medicationKindField;
        
        private bool medicationKindFieldSpecified;
        
        private string indicationField;
        
        private string patientInstructionsField;
        
        private string reactionField;
        
        private string vehicleField;
        
        private string doseIndicatorField;
        
        private string orderNumberField;
        
        private int fillsField;
        
        private bool fillsFieldSpecified;
        
        private string quantityOrderedField;
        
        private System.DateTime orderExpirationDateTimeField;
        
        private bool orderExpirationDateTimeFieldSpecified;
        
        private System.DateTime orderDateTimeField;
        
        private bool orderDateTimeFieldSpecified;
        
        private CodedValueType orderingProviderField;
        
        private System.DateTime lastUpdatedDateTimeField;
        
        private bool lastUpdatedDateTimeFieldSpecified;
        
        private int daysToTakeField;
        
        private bool daysToTakeFieldSpecified;
        
        private int quantityToDispenseField;
        
        private bool quantityToDispenseFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Administered {
            get {
                return this.administeredField;
            }
            set {
                this.administeredField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FreeTextSIG {
            get {
                return this.freeTextSIGField;
            }
            set {
                this.freeTextSIGField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime StartDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateTimeSpecified {
            get {
                return this.startDateTimeFieldSpecified;
            }
            set {
                this.startDateTimeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime StopDateTime {
            get {
                return this.stopDateTimeField;
            }
            set {
                this.stopDateTimeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StopDateTimeSpecified {
            get {
                return this.stopDateTimeFieldSpecified;
            }
            set {
                this.stopDateTimeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AdminTiming {
            get {
                return this.adminTimingField;
            }
            set {
                this.adminTimingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Interval {
            get {
                return this.intervalField;
            }
            set {
                this.intervalField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Route Route {
            get {
                return this.routeField;
            }
            set {
                this.routeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RouteSpecified {
            get {
                return this.routeFieldSpecified;
            }
            set {
                this.routeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Dose {
            get {
                return this.doseField;
            }
            set {
                this.doseField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DoseUnits {
            get {
                return this.doseUnitsField;
            }
            set {
                this.doseUnitsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DoseRestriction {
            get {
                return this.doseRestrictionField;
            }
            set {
                this.doseRestrictionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public ProductForm ProductForm {
            get {
                return this.productFormField;
            }
            set {
                this.productFormField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductFormSpecified {
            get {
                return this.productFormFieldSpecified;
            }
            set {
                this.productFormFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string DeliveryMethod {
            get {
                return this.deliveryMethodField;
            }
            set {
                this.deliveryMethodField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string BrandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string DrugManufacturer {
            get {
                return this.drugManufacturerField;
            }
            set {
                this.drugManufacturerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ProductConcentration {
            get {
                return this.productConcentrationField;
            }
            set {
                this.productConcentrationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public MedicationKind MedicationKind {
            get {
                return this.medicationKindField;
            }
            set {
                this.medicationKindField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MedicationKindSpecified {
            get {
                return this.medicationKindFieldSpecified;
            }
            set {
                this.medicationKindFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Indication {
            get {
                return this.indicationField;
            }
            set {
                this.indicationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string PatientInstructions {
            get {
                return this.patientInstructionsField;
            }
            set {
                this.patientInstructionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Reaction {
            get {
                return this.reactionField;
            }
            set {
                this.reactionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string DoseIndicator {
            get {
                return this.doseIndicatorField;
            }
            set {
                this.doseIndicatorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int Fills {
            get {
                return this.fillsField;
            }
            set {
                this.fillsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FillsSpecified {
            get {
                return this.fillsFieldSpecified;
            }
            set {
                this.fillsFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string QuantityOrdered {
            get {
                return this.quantityOrderedField;
            }
            set {
                this.quantityOrderedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public System.DateTime OrderExpirationDateTime {
            get {
                return this.orderExpirationDateTimeField;
            }
            set {
                this.orderExpirationDateTimeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderExpirationDateTimeSpecified {
            get {
                return this.orderExpirationDateTimeFieldSpecified;
            }
            set {
                this.orderExpirationDateTimeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public System.DateTime OrderDateTime {
            get {
                return this.orderDateTimeField;
            }
            set {
                this.orderDateTimeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderDateTimeSpecified {
            get {
                return this.orderDateTimeFieldSpecified;
            }
            set {
                this.orderDateTimeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public CodedValueType OrderingProvider {
            get {
                return this.orderingProviderField;
            }
            set {
                this.orderingProviderField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public System.DateTime LastUpdatedDateTime {
            get {
                return this.lastUpdatedDateTimeField;
            }
            set {
                this.lastUpdatedDateTimeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastUpdatedDateTimeSpecified {
            get {
                return this.lastUpdatedDateTimeFieldSpecified;
            }
            set {
                this.lastUpdatedDateTimeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public int DaysToTake {
            get {
                return this.daysToTakeField;
            }
            set {
                this.daysToTakeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysToTakeSpecified {
            get {
                return this.daysToTakeFieldSpecified;
            }
            set {
                this.daysToTakeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public int QuantityToDispense {
            get {
                return this.quantityToDispenseField;
            }
            set {
                this.quantityToDispenseField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityToDispenseSpecified {
            get {
                return this.quantityToDispenseFieldSpecified;
            }
            set {
                this.quantityToDispenseFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class Result : ClinicalItemBase {
        
        private string resultNameField;
        
        private System.DateTime resultDateTimeField;
        
        private string valueField;
        
        private string unitsField;
        
        private string unitsModifierField;
        
        private string interpretationField;
        
        private string referenceRangeField;
        
        private CodedValueType providerIDField;
        
        private CodedValueType labOrderIDField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ResultName {
            get {
                return this.resultNameField;
            }
            set {
                this.resultNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ResultDateTime {
            get {
                return this.resultDateTimeField;
            }
            set {
                this.resultDateTimeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UnitsModifier {
            get {
                return this.unitsModifierField;
            }
            set {
                this.unitsModifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Interpretation {
            get {
                return this.interpretationField;
            }
            set {
                this.interpretationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ReferenceRange {
            get {
                return this.referenceRangeField;
            }
            set {
                this.referenceRangeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public CodedValueType ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public CodedValueType LabOrderID {
            get {
                return this.labOrderIDField;
            }
            set {
                this.labOrderIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class LabOrder : ClinicalItemBase {
        
        private string orderNameField;
        
        private System.DateTime orderDateTimeField;
        
        private CodedValueType providerIDField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OrderName {
            get {
                return this.orderNameField;
            }
            set {
                this.orderNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime OrderDateTime {
            get {
                return this.orderDateTimeField;
            }
            set {
                this.orderDateTimeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CodedValueType ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class Allergy : ClinicalItemBase {
        
        private System.DateTime eventDateField;
        
        private bool eventDateFieldSpecified;
        
        private AdverseEventType eventTypeField;
        
        private bool eventTypeFieldSpecified;
        
        private string productTextField;
        
        private List<AllergyReaction> reactionsField;
        
        private string severityTextField;
        
        private ProblemSeverity severityCodeField;
        
        private bool severityCodeFieldSpecified;
        
        private CodedValueType providerIDField;
        
        public Allergy() {
            this.reactionsField = new List<AllergyReaction>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime EventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventDateSpecified {
            get {
                return this.eventDateFieldSpecified;
            }
            set {
                this.eventDateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AdverseEventType EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventTypeSpecified {
            get {
                return this.eventTypeFieldSpecified;
            }
            set {
                this.eventTypeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProductText {
            get {
                return this.productTextField;
            }
            set {
                this.productTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Reaction", IsNullable=false)]
        public List<AllergyReaction> Reactions {
            get {
                return this.reactionsField;
            }
            set {
                this.reactionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SeverityText {
            get {
                return this.severityTextField;
            }
            set {
                this.severityTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ProblemSeverity SeverityCode {
            get {
                return this.severityCodeField;
            }
            set {
                this.severityCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeverityCodeSpecified {
            get {
                return this.severityCodeFieldSpecified;
            }
            set {
                this.severityCodeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public CodedValueType ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Allscripts:momci")]
    public partial class AllergyReaction {
        
        private string reactionTextField;
        
        private CodedValueType reactionCodeField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReactionText {
            get {
                return this.reactionTextField;
            }
            set {
                this.reactionTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CodedValueType ReactionCode {
            get {
                return this.reactionCodeField;
            }
            set {
                this.reactionCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class PlanOfCare : ClinicalItemBase {
        
        private string orderTextField;
        
        private System.DateTime orderDateField;
        
        private bool orderDateFieldSpecified;
        
        private int orderProviderField;
        
        private bool orderProviderFieldSpecified;
        
        private string orderPriorityField;
        
        private string orderFrequencyField;
        
        private bool deferredFlagField;
        
        private bool deferredFlagFieldSpecified;
        
        private System.DateTime deferredUntilDateField;
        
        private bool deferredUntilDateFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OrderText {
            get {
                return this.orderTextField;
            }
            set {
                this.orderTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderDateSpecified {
            get {
                return this.orderDateFieldSpecified;
            }
            set {
                this.orderDateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int OrderProvider {
            get {
                return this.orderProviderField;
            }
            set {
                this.orderProviderField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderProviderSpecified {
            get {
                return this.orderProviderFieldSpecified;
            }
            set {
                this.orderProviderFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OrderPriority {
            get {
                return this.orderPriorityField;
            }
            set {
                this.orderPriorityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OrderFrequency {
            get {
                return this.orderFrequencyField;
            }
            set {
                this.orderFrequencyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool DeferredFlag {
            get {
                return this.deferredFlagField;
            }
            set {
                this.deferredFlagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeferredFlagSpecified {
            get {
                return this.deferredFlagFieldSpecified;
            }
            set {
                this.deferredFlagFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime DeferredUntilDate {
            get {
                return this.deferredUntilDateField;
            }
            set {
                this.deferredUntilDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeferredUntilDateSpecified {
            get {
                return this.deferredUntilDateFieldSpecified;
            }
            set {
                this.deferredUntilDateFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=false)]
    public partial class Immunization : ClinicalItemBase {
        
        private string productNameField;
        
        private System.DateTime administeredDateField;
        
        private bool administeredDateFieldSpecified;
        
        private string doseField;
        
        private string doseUnitsField;
        
        private List<CodedValueType> administrationNotesField;
        
        private Provider administeringProviderField;
        
        private Organization administeringLocationField;
        
        private List<string> substanceLotNumberField;
        
        private System.DateTime vaccineExpirationDateField;
        
        private bool vaccineExpirationDateFieldSpecified;
        
        private List<string> substanceManufacturerNameField;
        
        private string medicationSeriesNumberField;
        
        private List<CodedValueType> refusalReasonField;
        
        private CodedValueType indicationField;
        
        private CodedValueType completionStatusField;
        
        private CodedValueType routeField;
        
        private List<CodedValueType> administrationSiteField;
        
        private List<ReactionObservation> reactionObservationField;
        
        private List<ImmunizationVaccinationComponent> vaccinationComponentField;
        
        private CodedValueType immunizationScheduleUsedField;
        
        private string medicationSeriesNameField;
        
        private CodedValueType administeringProviderIDField;
        
        public Immunization() {
            this.vaccinationComponentField = new List<ImmunizationVaccinationComponent>();
            this.reactionObservationField = new List<ReactionObservation>();
            this.administrationSiteField = new List<CodedValueType>();
            this.refusalReasonField = new List<CodedValueType>();
            this.substanceManufacturerNameField = new List<string>();
            this.substanceLotNumberField = new List<string>();
            this.administeringLocationField = new Organization();
            this.administeringProviderField = new Provider();
            this.administrationNotesField = new List<CodedValueType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime AdministeredDate {
            get {
                return this.administeredDateField;
            }
            set {
                this.administeredDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdministeredDateSpecified {
            get {
                return this.administeredDateFieldSpecified;
            }
            set {
                this.administeredDateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Dose {
            get {
                return this.doseField;
            }
            set {
                this.doseField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DoseUnits {
            get {
                return this.doseUnitsField;
            }
            set {
                this.doseUnitsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AdministrationNotes", Order=4)]
        public List<CodedValueType> AdministrationNotes {
            get {
                return this.administrationNotesField;
            }
            set {
                this.administrationNotesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Provider AdministeringProvider {
            get {
                return this.administeringProviderField;
            }
            set {
                this.administeringProviderField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Organization AdministeringLocation {
            get {
                return this.administeringLocationField;
            }
            set {
                this.administeringLocationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SubstanceLotNumber", Order=7)]
        public List<string> SubstanceLotNumber {
            get {
                return this.substanceLotNumberField;
            }
            set {
                this.substanceLotNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=8)]
        public System.DateTime VaccineExpirationDate {
            get {
                return this.vaccineExpirationDateField;
            }
            set {
                this.vaccineExpirationDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VaccineExpirationDateSpecified {
            get {
                return this.vaccineExpirationDateFieldSpecified;
            }
            set {
                this.vaccineExpirationDateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SubstanceManufacturerName", Order=9)]
        public List<string> SubstanceManufacturerName {
            get {
                return this.substanceManufacturerNameField;
            }
            set {
                this.substanceManufacturerNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MedicationSeriesNumber {
            get {
                return this.medicationSeriesNumberField;
            }
            set {
                this.medicationSeriesNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("RefusalReason", Order=11)]
        public List<CodedValueType> RefusalReason {
            get {
                return this.refusalReasonField;
            }
            set {
                this.refusalReasonField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public CodedValueType Indication {
            get {
                return this.indicationField;
            }
            set {
                this.indicationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public CodedValueType CompletionStatus {
            get {
                return this.completionStatusField;
            }
            set {
                this.completionStatusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public CodedValueType Route {
            get {
                return this.routeField;
            }
            set {
                this.routeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("code", IsNullable=false)]
        public List<CodedValueType> AdministrationSite {
            get {
                return this.administrationSiteField;
            }
            set {
                this.administrationSiteField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ReactionObservation", Order=16)]
        public List<ReactionObservation> ReactionObservation {
            get {
                return this.reactionObservationField;
            }
            set {
                this.reactionObservationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("VaccinationComponent", Order=17)]
        public List<ImmunizationVaccinationComponent> VaccinationComponent {
            get {
                return this.vaccinationComponentField;
            }
            set {
                this.vaccinationComponentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public CodedValueType ImmunizationScheduleUsed {
            get {
                return this.immunizationScheduleUsedField;
            }
            set {
                this.immunizationScheduleUsedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string MedicationSeriesName {
            get {
                return this.medicationSeriesNameField;
            }
            set {
                this.medicationSeriesNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public CodedValueType AdministeringProviderID {
            get {
                return this.administeringProviderIDField;
            }
            set {
                this.administeringProviderIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=true)]
    public partial class ReactionObservation {
        
        private List<CodedValueType> reactionCodeField;
        
        private System.DateTime observationDateTimeField;
        
        public ReactionObservation() {
            this.reactionCodeField = new List<CodedValueType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ReactionCode", Order=0)]
        public List<CodedValueType> ReactionCode {
            get {
                return this.reactionCodeField;
            }
            set {
                this.reactionCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime ObservationDateTime {
            get {
                return this.observationDateTimeField;
            }
            set {
                this.observationDateTimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Allscripts:momci")]
    public partial class ImmunizationVaccinationComponent {
        
        private CodedValueType vaccinationGroupField;
        
        private VaccineInformationStatement vaccineInformationStatementField;
        
        public ImmunizationVaccinationComponent() {
            this.vaccineInformationStatementField = new VaccineInformationStatement();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CodedValueType VaccinationGroup {
            get {
                return this.vaccinationGroupField;
            }
            set {
                this.vaccinationGroupField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VaccineInformationStatement VaccineInformationStatement {
            get {
                return this.vaccineInformationStatementField;
            }
            set {
                this.vaccineInformationStatementField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momci")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momci", IsNullable=true)]
    public partial class VaccineInformationStatement {
        
        private System.DateTime publicationDateField;
        
        private bool publicationDateFieldSpecified;
        
        private System.DateTime receiptDateField;
        
        private bool receiptDateFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime PublicationDate {
            get {
                return this.publicationDateField;
            }
            set {
                this.publicationDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublicationDateSpecified {
            get {
                return this.publicationDateFieldSpecified;
            }
            set {
                this.publicationDateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime ReceiptDate {
            get {
                return this.receiptDateField;
            }
            set {
                this.receiptDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceiptDateSpecified {
            get {
                return this.receiptDateFieldSpecified;
            }
            set {
                this.receiptDateFieldSpecified = value;
            }
        }
    }
}
