// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Allscripts.Model</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Allscripts.Model {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Allscripts:momst")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Allscripts:momst", IsNullable=false)]
    public partial class RequiredForGeneration {
        
        private AddressType addressTypeField;
        
        private CurrencyCodeValue currencyCodeValueField;
        
        private NameType nameTypeField;
        
        private PhoneType phoneTypeField;
        
        private TelecommunicationUse telecommunicationUseField;
        
        private TelecommunicationEquipmentType telecommunicationEquipmentTypeField;
        
        private Gender genderField;
        
        private LanguageName languageNameField;
        
        private MaritalStatus maritalStatusField;
        
        private StatusType statusTypeField;
        
        private EthnicDescription ethnicDescriptionField;
        
        private RaceDescription raceDescriptionField;
        
        private TypeOfReferral typeOfReferralField;
        
        private LivingArrangement livingArrangementField;
        
        private LivingDependency livingDependencyField;
        
        private int referralStatusField;
        
        private int arnMatchCriteriaField;
        
        private string jobStatusField;
        
        private VitalSignType vitalSignTypeField;
        
        private VitalSignUnit vitalSignUnitField;
        
        private AdverseEventType adverseEventTypeField;
        
        private ProblemSeverity problemSeverityField;
        
        private Route routeField;
        
        private ProductForm productFormField;
        
        private MedicationKind medicationKindField;
        
        private ProblemType problemTypeField;
        
        private SocialHistoryType socialHistoryTypeField;
        
        private ClinicalItemStatus clinicalItemStatusField;
        
        private InsuranceType insuranceTypeField;
        
        private SubscriberRelationship subscriberRelationshipField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressType AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CurrencyCodeValue CurrencyCodeValue {
            get {
                return this.currencyCodeValueField;
            }
            set {
                this.currencyCodeValueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public NameType NameType {
            get {
                return this.nameTypeField;
            }
            set {
                this.nameTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PhoneType PhoneType {
            get {
                return this.phoneTypeField;
            }
            set {
                this.phoneTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TelecommunicationUse TelecommunicationUse {
            get {
                return this.telecommunicationUseField;
            }
            set {
                this.telecommunicationUseField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TelecommunicationEquipmentType TelecommunicationEquipmentType {
            get {
                return this.telecommunicationEquipmentTypeField;
            }
            set {
                this.telecommunicationEquipmentTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Gender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public LanguageName LanguageName {
            get {
                return this.languageNameField;
            }
            set {
                this.languageNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public MaritalStatus MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public StatusType StatusType {
            get {
                return this.statusTypeField;
            }
            set {
                this.statusTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public EthnicDescription EthnicDescription {
            get {
                return this.ethnicDescriptionField;
            }
            set {
                this.ethnicDescriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public RaceDescription RaceDescription {
            get {
                return this.raceDescriptionField;
            }
            set {
                this.raceDescriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public TypeOfReferral TypeOfReferral {
            get {
                return this.typeOfReferralField;
            }
            set {
                this.typeOfReferralField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public LivingArrangement LivingArrangement {
            get {
                return this.livingArrangementField;
            }
            set {
                this.livingArrangementField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public LivingDependency LivingDependency {
            get {
                return this.livingDependencyField;
            }
            set {
                this.livingDependencyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int ReferralStatus {
            get {
                return this.referralStatusField;
            }
            set {
                this.referralStatusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int ArnMatchCriteria {
            get {
                return this.arnMatchCriteriaField;
            }
            set {
                this.arnMatchCriteriaField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string JobStatus {
            get {
                return this.jobStatusField;
            }
            set {
                this.jobStatusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public VitalSignType VitalSignType {
            get {
                return this.vitalSignTypeField;
            }
            set {
                this.vitalSignTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public VitalSignUnit VitalSignUnit {
            get {
                return this.vitalSignUnitField;
            }
            set {
                this.vitalSignUnitField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public AdverseEventType AdverseEventType {
            get {
                return this.adverseEventTypeField;
            }
            set {
                this.adverseEventTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public ProblemSeverity ProblemSeverity {
            get {
                return this.problemSeverityField;
            }
            set {
                this.problemSeverityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public Route Route {
            get {
                return this.routeField;
            }
            set {
                this.routeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public ProductForm ProductForm {
            get {
                return this.productFormField;
            }
            set {
                this.productFormField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public MedicationKind MedicationKind {
            get {
                return this.medicationKindField;
            }
            set {
                this.medicationKindField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public ProblemType ProblemType {
            get {
                return this.problemTypeField;
            }
            set {
                this.problemTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public SocialHistoryType SocialHistoryType {
            get {
                return this.socialHistoryTypeField;
            }
            set {
                this.socialHistoryTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public ClinicalItemStatus ClinicalItemStatus {
            get {
                return this.clinicalItemStatusField;
            }
            set {
                this.clinicalItemStatusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public InsuranceType InsuranceType {
            get {
                return this.insuranceTypeField;
            }
            set {
                this.insuranceTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public SubscriberRelationship SubscriberRelationship {
            get {
                return this.subscriberRelationshipField;
            }
            set {
                this.subscriberRelationshipField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum AddressType {
        
        /// <remarks/>
        Billing,
        
        /// <remarks/>
        Birth,
        
        /// <remarks/>
        Temporary,
        
        /// <remarks/>
        Home,
        
        /// <remarks/>
        Communication,
        
        /// <remarks/>
        Mailing,
        
        /// <remarks/>
        CountryOfOrigin,
        
        /// <remarks/>
        Office,
        
        /// <remarks/>
        Business,
        
        /// <remarks/>
        Permanent,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum CurrencyCodeValue {
        
        /// <remarks/>
        USD,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum NameType {
        
        /// <remarks/>
        Adopted,
        
        /// <remarks/>
        Alias,
        
        /// <remarks/>
        BirthName,
        
        /// <remarks/>
        Legal,
        
        /// <remarks/>
        Maiden,
        
        /// <remarks/>
        Preferred,
        
        /// <remarks/>
        Unspecified,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum PhoneType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum TelecommunicationUse {
        
        /// <remarks/>
        AnsweringServiceNumber,
        
        /// <remarks/>
        CellularPhone,
        
        /// <remarks/>
        EmergencyNumber,
        
        /// <remarks/>
        HomeNumber,
        
        /// <remarks/>
        VacationHomeNumber,
        
        /// <remarks/>
        OtherResidenceNumber,
        
        /// <remarks/>
        WorkNumber,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum TelecommunicationEquipmentType {
        
        /// <remarks/>
        Telephone,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Modem,
        
        /// <remarks/>
        CellularPhone,
        
        /// <remarks/>
        Beeper,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum Gender {
        
        /// <remarks/>
        Female,
        
        /// <remarks/>
        Male,
        
        /// <remarks/>
        Undifferentiated,
        
        /// <remarks/>
        undifferentiated,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        U,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        f,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        u,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum LanguageName {
        
        /// <remarks/>
        English,
        
        /// <remarks/>
        Spanish,
        
        /// <remarks/>
        French,
        
        /// <remarks/>
        German,
        
        /// <remarks/>
        Irish,
        
        /// <remarks/>
        Italian,
        
        /// <remarks/>
        Hatian,
        
        /// <remarks/>
        Hebrew,
        
        /// <remarks/>
        Japanese,
        
        /// <remarks/>
        Polish,
        
        /// <remarks/>
        Russian,
        
        /// <remarks/>
        Chinese,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Cantonese Chinese")]
        CantoneseChinese,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mandarin Chinese")]
        MandarinChinese,
        
        /// <remarks/>
        Sign,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Sign Language")]
        SignLanguage,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum MaritalStatus {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        Annulled,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        Divorced,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        Interlocutory,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Legally separated")]
        Legallyseparated,
        
        /// <remarks/>
        Separated,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        Married,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        Polygamous,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Big Love")]
        BigLove,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Domestic partner")]
        Domesticpartner,
        
        /// <remarks/>
        Partner,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        Widowed,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum StatusType {
        
        /// <remarks/>
        military,
        
        /// <remarks/>
        marital,
        
        /// <remarks/>
        student,
        
        /// <remarks/>
        employment,
        
        /// <remarks/>
        active,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum EthnicDescription {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Central American")]
        CentralAmerican,
        
        /// <remarks/>
        Cuban,
        
        /// <remarks/>
        Dominican,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Latin American")]
        LatinAmerican,
        
        /// <remarks/>
        Mexican,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Puerto Rican")]
        PuertoRican,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("South American")]
        SouthAmerican,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Hispanic or Latino")]
        HispanicorLatino,
        
        /// <remarks/>
        Hispanic,
        
        /// <remarks/>
        Latino,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Not Hispanic or Latino")]
        NotHispanicorLatino,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Not Hispanic")]
        NotHispanic,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Not Latino")]
        NotLatino,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum RaceDescription {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Alaskan Native")]
        AlaskanNative,
        
        /// <remarks/>
        Alaskan,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("American Indian")]
        AmericanIndian,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Native American")]
        NativeAmerican,
        
        /// <remarks/>
        Asian,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Black or African American")]
        BlackorAfricanAmerican,
        
        /// <remarks/>
        Black,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("African American")]
        AfricanAmerican,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Native Hawaiian or other Pacific Islander")]
        NativeHawaiianorotherPacificIslander,
        
        /// <remarks/>
        Hawaiian,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pacific Islander")]
        PacificIslander,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Other Race")]
        OtherRace,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        White,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum TypeOfReferral {
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        T,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum LivingArrangement {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        U,
        
        /// <remarks/>
        S,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum LivingDependency {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        O,
        
        /// <remarks/>
        U,
        
        /// <remarks/>
        P,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum VitalSignType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Respiratory Rate")]
        RespiratoryRate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resipration Rate")]
        ResiprationRate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Heart Rate")]
        HeartRate,
        
        /// <remarks/>
        Pulse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("O2 SAT")]
        O2SAT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BP Systolic")]
        BPSystolic,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BP Diastolic")]
        BPDiastolic,
        
        /// <remarks/>
        Temperature,
        
        /// <remarks/>
        Height,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Height (Lying)")]
        HeightLying,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Head Circumference")]
        HeadCircumference,
        
        /// <remarks/>
        Weight,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum VitalSignUnit {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("/min")]
        min,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("%")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mm[Hg]")]
        mmHg,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        c,
        
        /// <remarks/>
        Cel,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        f,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        cm,
        
        /// <remarks/>
        @in,
        
        /// <remarks/>
        kg,
        
        /// <remarks/>
        g,
        
        /// <remarks/>
        lb,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum AdverseEventType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("allergy to substance")]
        allergytosubstance,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("drug allergy")]
        drugallergy,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("food allergy")]
        foodallergy,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("drug intolerance")]
        drugintolerance,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("food intolerance")]
        foodintolerance,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("propensity to adverse reactions")]
        propensitytoadversereactions,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("propensity to adverse reactions to substance")]
        propensitytoadversereactionstosubstance,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("propensity to adverse reactions to drug")]
        propensitytoadversereactionstodrug,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("propensity to adverse reactions to food")]
        propensitytoadversereactionstofood,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum ProblemSeverity {
        
        /// <remarks/>
        Mild,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mild to moderate")]
        Mildtomoderate,
        
        /// <remarks/>
        Moderate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Moderate to severe")]
        Moderatetosevere,
        
        /// <remarks/>
        Severe,
        
        /// <remarks/>
        Fatal,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum Route {
        
        /// <remarks/>
        DENTAL,
        
        /// <remarks/>
        EPIDURAL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INTRA-ARTICULAR")]
        INTRAARTICULAR,
        
        /// <remarks/>
        INTRACAVERNOUS,
        
        /// <remarks/>
        INTRADERMAL,
        
        /// <remarks/>
        INTRAMUSCULAR,
        
        /// <remarks/>
        INTRAOCULAR,
        
        /// <remarks/>
        INTRAPERITONEAL,
        
        /// <remarks/>
        INTRAPLEURAL,
        
        /// <remarks/>
        INTRATHECAL,
        
        /// <remarks/>
        INTRAUTERINE,
        
        /// <remarks/>
        INTRAVENOUS,
        
        /// <remarks/>
        INTRAVESICAL,
        
        /// <remarks/>
        IRRIGATION,
        
        /// <remarks/>
        NASAL,
        
        /// <remarks/>
        OPHTHALMIC,
        
        /// <remarks/>
        ORAL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("AURICULAR (OTIC)")]
        AURICULAROTIC,
        
        /// <remarks/>
        RECTAL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("RESPIRATORY (INHALATION)")]
        RESPIRATORYINHALATION,
        
        /// <remarks/>
        SUBCUTANEOUS,
        
        /// <remarks/>
        SUBLINGUAL,
        
        /// <remarks/>
        TRANSDERMAL,
        
        /// <remarks/>
        URETHRAL,
        
        /// <remarks/>
        VAGINAL,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum ProductForm {
        
        /// <remarks/>
        AEROSOL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("AEROSOL, FOAM")]
        AEROSOLFOAM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("AEROSOL, METERED")]
        AEROSOLMETERED,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("AEROSOL, POWDER")]
        AEROSOLPOWDER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("AEROSOL, SPRAY")]
        AEROSOLSPRAY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BAR, CHEWABLE")]
        BARCHEWABLE,
        
        /// <remarks/>
        BEAD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BEAD, IMPLANT, EXTENDED RELEASE")]
        BEADIMPLANTEXTENDEDRELEASE,
        
        /// <remarks/>
        BLOCK,
        
        /// <remarks/>
        CAPSULE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CAPSULE, COATED")]
        CAPSULECOATED,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CAPSULE, COATED PELLETS")]
        CAPSULECOATEDPELLETS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CAPSULE, COATED, EXTENDED RELEASE")]
        CAPSULECOATEDEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CAPSULE, DELAYED RELEASE")]
        CAPSULEDELAYEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CAPSULE, DELAYED RELEASE PELLETS")]
        CAPSULEDELAYEDRELEASEPELLETS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CAPSULE, EXTENDED RELEASE")]
        CAPSULEEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CAPSULE, FILM COATED, EXTENDED RELEASE")]
        CAPSULEFILMCOATEDEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CAPSULE, GELATIN COATED")]
        CAPSULEGELATINCOATED,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CAPSULE, LIQUID FILLED")]
        CAPSULELIQUIDFILLED,
        
        /// <remarks/>
        CEMENT,
        
        /// <remarks/>
        CIGARETTE,
        
        /// <remarks/>
        CLOTH,
        
        /// <remarks/>
        CONCENTRATE,
        
        /// <remarks/>
        CONE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CORE, EXTENDED RELEASE")]
        COREEXTENDEDRELEASE,
        
        /// <remarks/>
        CREAM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CREAM, AUGMENTED")]
        CREAMAUGMENTED,
        
        /// <remarks/>
        CRYSTAL,
        
        /// <remarks/>
        CULTURE,
        
        /// <remarks/>
        DIAPHRAGM,
        
        /// <remarks/>
        DISC,
        
        /// <remarks/>
        DOUCHE,
        
        /// <remarks/>
        DRESSING,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DRUG DELIVERY SYSTEM")]
        DRUGDELIVERYSYSTEM,
        
        /// <remarks/>
        ELIXIR,
        
        /// <remarks/>
        EMULSION,
        
        /// <remarks/>
        ENEMA,
        
        /// <remarks/>
        EXTRACT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("FIBER, EXTENDED RELEASE")]
        FIBEREXTENDEDRELEASE,
        
        /// <remarks/>
        FILM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("FILM, EXTENDED RELEASE")]
        FILMEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("FILM, SOLUBLE")]
        FILMSOLUBLE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("FOR SOLUTION")]
        FORSOLUTION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("FOR SUSPENSION")]
        FORSUSPENSION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("FOR SUSPENSION, EXTENDED RELEASE")]
        FORSUSPENSIONEXTENDEDRELEASE,
        
        /// <remarks/>
        GAS,
        
        /// <remarks/>
        GEL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("GEL, DENTIFRICE")]
        GELDENTIFRICE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("GEL, METERED")]
        GELMETERED,
        
        /// <remarks/>
        GENERATOR,
        
        /// <remarks/>
        GLOBULE,
        
        /// <remarks/>
        GRAFT,
        
        /// <remarks/>
        GRANULE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("GRANULE, DELAYED RELEASE")]
        GRANULEDELAYEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("GRANULE, EFFERVESCENT")]
        GRANULEEFFERVESCENT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("GRANULE, FOR SOLUTION")]
        GRANULEFORSOLUTION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("GRANULE, FOR SUSPENSION")]
        GRANULEFORSUSPENSION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("GRANULE, FOR SUSPENSION, EXTENDED RELEASE")]
        GRANULEFORSUSPENSIONEXTENDEDRELEASE,
        
        /// <remarks/>
        GUM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("GUM, CHEWING")]
        GUMCHEWING,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("GUM, RESIN")]
        GUMRESIN,
        
        /// <remarks/>
        IMPLANT,
        
        /// <remarks/>
        INHALANT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTABLE, LIPOSOMAL")]
        INJECTABLELIPOSOMAL,
        
        /// <remarks/>
        INJECTION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, EMULSION")]
        INJECTIONEMULSION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, LIPID COMPLEX")]
        INJECTIONLIPIDCOMPLEX,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, POWDER, FOR SOLUTION")]
        INJECTIONPOWDERFORSOLUTION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, POWDER, FOR SUSPENSION")]
        INJECTIONPOWDERFORSUSPENSION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, POWDER, FOR SUSPENSION, EXTENDED RELEASE")]
        INJECTIONPOWDERFORSUSPENSIONEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, POWDER, LYOPHILIZED, FOR LIPOSOMAL SUSPENSION")]
        INJECTIONPOWDERLYOPHILIZEDFORLIPOSOMALSUSPENSION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, POWDER, LYOPHILIZED, FOR SOLUTION")]
        INJECTIONPOWDERLYOPHILIZEDFORSOLUTION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, POWDER, LYOPHILIZED, FOR SUSPENSION")]
        INJECTIONPOWDERLYOPHILIZEDFORSUSPENSION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, POWDER, LYOPHILIZED, FOR SUSPENSION, EXTENDED RELEASE")]
        INJECTIONPOWDERLYOPHILIZEDFORSUSPENSIONEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, SOLUTION")]
        INJECTIONSOLUTION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, SOLUTION, CONCENTRATE")]
        INJECTIONSOLUTIONCONCENTRATE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, SUSPENSION")]
        INJECTIONSUSPENSION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, SUSPENSION, EXTENDED RELEASE")]
        INJECTIONSUSPENSIONEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, SUSPENSION, LIPOSOMAL")]
        INJECTIONSUSPENSIONLIPOSOMAL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INJECTION, SUSPENSION, SONICATED")]
        INJECTIONSUSPENSIONSONICATED,
        
        /// <remarks/>
        INSERT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INSERT, EXTENDED RELEASE")]
        INSERTEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INTRAUTERINE DEVICE")]
        INTRAUTERINEDEVICE,
        
        /// <remarks/>
        IRRIGANT,
        
        /// <remarks/>
        JELLY,
        
        /// <remarks/>
        KIT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LINER, DENTAL")]
        LINERDENTAL,
        
        /// <remarks/>
        LINIMENT,
        
        /// <remarks/>
        LIPSTICK,
        
        /// <remarks/>
        LIQUID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LIQUID, EXTENDED RELEASE")]
        LIQUIDEXTENDEDRELEASE,
        
        /// <remarks/>
        LOTION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LOTION, AUGMENTED")]
        LOTIONAUGMENTED,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LOTION/SHAMPOO")]
        LOTIONSHAMPOO,
        
        /// <remarks/>
        LOZENGE,
        
        /// <remarks/>
        MOUTHWASH,
        
        /// <remarks/>
        OIL,
        
        /// <remarks/>
        OINTMENT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OINTMENT, AUGMENTED")]
        OINTMENTAUGMENTED,
        
        /// <remarks/>
        PACKING,
        
        /// <remarks/>
        PASTE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PASTE, DENTIFRICE")]
        PASTEDENTIFRICE,
        
        /// <remarks/>
        PASTILLE,
        
        /// <remarks/>
        PATCH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PATCH, EXTENDED RELEASE")]
        PATCHEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PATCH, EXTENDED RELEASE, ELECTRICALLY CONTROLLED")]
        PATCHEXTENDEDRELEASEELECTRICALLYCONTROLLED,
        
        /// <remarks/>
        PELLET,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PELLET, IMPLANTABLE")]
        PELLETIMPLANTABLE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PELLETS, COATED, EXTENDED RELEASE")]
        PELLETSCOATEDEXTENDEDRELEASE,
        
        /// <remarks/>
        PILL,
        
        /// <remarks/>
        PLASTER,
        
        /// <remarks/>
        POULTICE,
        
        /// <remarks/>
        POWDER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("POWDER, DENTIFRICE")]
        POWDERDENTIFRICE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("POWDER, FOR SOLUTION")]
        POWDERFORSOLUTION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("POWDER, FOR SUSPENSION")]
        POWDERFORSUSPENSION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("POWDER, METERED")]
        POWDERMETERED,
        
        /// <remarks/>
        RING,
        
        /// <remarks/>
        RINSE,
        
        /// <remarks/>
        SALVE,
        
        /// <remarks/>
        SHAMPOO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SHAMPOO, SUSPENSION")]
        SHAMPOOSUSPENSION,
        
        /// <remarks/>
        SOAP,
        
        /// <remarks/>
        SOLUTION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SOLUTION, CONCENTRATE")]
        SOLUTIONCONCENTRATE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SOLUTION, FOR SLUSH")]
        SOLUTIONFORSLUSH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SOLUTION, GEL FORMING / DROPS")]
        SOLUTIONGELFORMINGDROPS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SOLUTION, GEL FORMING, EXTENDED RELEASE")]
        SOLUTIONGELFORMINGEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SOLUTION/ DROPS")]
        SOLUTIONDROPS,
        
        /// <remarks/>
        SPONGE,
        
        /// <remarks/>
        SPRAY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SPRAY, METERED")]
        SPRAYMETERED,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SPRAY, SUSPENSION")]
        SPRAYSUSPENSION,
        
        /// <remarks/>
        STICK,
        
        /// <remarks/>
        STRIP,
        
        /// <remarks/>
        SUPPOSITORY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SUPPOSITORY, EXTENDED RELEASE")]
        SUPPOSITORYEXTENDEDRELEASE,
        
        /// <remarks/>
        SUSPENSION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SUSPENSION, EXTENDED RELEASE")]
        SUSPENSIONEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SUSPENSION/ DROPS")]
        SUSPENSIONDROPS,
        
        /// <remarks/>
        SUTURE,
        
        /// <remarks/>
        SWAB,
        
        /// <remarks/>
        SYRUP,
        
        /// <remarks/>
        TABLET,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, CHEWABLE")]
        TABLETCHEWABLE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, COATED")]
        TABLETCOATED,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, COATED PARTICLES")]
        TABLETCOATEDPARTICLES,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, DELAYED RELEASE")]
        TABLETDELAYEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, DELAYED RELEASE PARTICLES")]
        TABLETDELAYEDRELEASEPARTICLES,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, EFFERVESCENT")]
        TABLETEFFERVESCENT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, EXTENDED RELEASE")]
        TABLETEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, FILM COATED")]
        TABLETFILMCOATED,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, FILM COATED, EXTENDED RELEASE")]
        TABLETFILMCOATEDEXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, FOR SOLUTION")]
        TABLETFORSOLUTION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, FOR SUSPENSION")]
        TABLETFORSUSPENSION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, MULTILAYER")]
        TABLETMULTILAYER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, MULTILAYER, EXTENDED RELEASE")]
        TABLETMULTILAYEREXTENDEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, ORALLY DISINTEGRATING")]
        TABLETORALLYDISINTEGRATING,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, ORALLY DISINTEGRATING, DELAYED RELEASE")]
        TABLETORALLYDISINTEGRATINGDELAYEDRELEASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, SOLUBLE")]
        TABLETSOLUBLE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TABLET, SUGAR COATED")]
        TABLETSUGARCOATED,
        
        /// <remarks/>
        TAMPON,
        
        /// <remarks/>
        TAPE,
        
        /// <remarks/>
        TINCTURE,
        
        /// <remarks/>
        TROCHE,
        
        /// <remarks/>
        UNASSIGNED,
        
        /// <remarks/>
        WAFER,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum MedicationKind {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("over the counter")]
        overthecounter,
        
        /// <remarks/>
        otc,
        
        /// <remarks/>
        OTC,
        
        /// <remarks/>
        prescription,
        
        /// <remarks/>
        rx,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum ProblemType {
        
        /// <remarks/>
        Finding,
        
        /// <remarks/>
        Symptom,
        
        /// <remarks/>
        Problem,
        
        /// <remarks/>
        Complaint,
        
        /// <remarks/>
        Condition,
        
        /// <remarks/>
        Diagnosis,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Functional limitation")]
        Functionallimitation,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum SocialHistoryType {
        
        /// <remarks/>
        Smoking,
        
        /// <remarks/>
        Exercise,
        
        /// <remarks/>
        Alcohol,
        
        /// <remarks/>
        Diet,
        
        /// <remarks/>
        Employment,
        
        /// <remarks/>
        Toxic,
        
        /// <remarks/>
        Drug,
        
        /// <remarks/>
        Other,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum ClinicalItemStatus {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Inactive,
        
        /// <remarks/>
        Complete,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Resolved,
        
        /// <remarks/>
        Transformed,
        
        /// <remarks/>
        Deleted,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Entered in Error")]
        EnteredinError,
        
        /// <remarks/>
        DC,
        
        /// <remarks/>
        Discontinued,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Partial,
        
        /// <remarks/>
        Unverified,
        
        /// <remarks/>
        Suspect,
        
        /// <remarks/>
        Denied,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Adverse Reaction")]
        AdverseReaction,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        Held,
        
        /// <remarks/>
        Canceled,
        
        /// <remarks/>
        Administered,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Admin Requested")]
        AdminRequested,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Filled Rx")]
        FilledRx,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Refill Requested")]
        RefillRequested,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Refill Denied")]
        RefillDenied,
        
        /// <remarks/>
        Void,
        
        /// <remarks/>
        Unauthorized,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Auto Complete")]
        AutoComplete,
        
        /// <remarks/>
        Chronic,
        
        /// <remarks/>
        Permanent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Assumed Resolved")]
        AssumedResolved,
        
        /// <remarks/>
        Temporary,
        
        /// <remarks/>
        Transitioned,
        
        /// <remarks/>
        Acute,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Final,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Final, Reviewed")]
        FinalReviewed,
        
        /// <remarks/>
        Ordered,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Prior History")]
        PriorHistory,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No Longer Active")]
        NoLongerActive,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum InsuranceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Secondary Working Aged Beneficiary or Spouse with Employer Group Health " +
            "Plan")]
        MedicareSecondaryWorkingAgedBeneficiaryorSpousewithEmployerGroupHealthPlan,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Secondary End-Stage Renal Disease Beneficiary in the 12 month coordinati" +
            "on period with an employer\'s group health plan")]
        MedicareSecondaryEndStageRenalDiseaseBeneficiaryinthe12monthcoordinationperiodwithanemployersgrouphealthplan,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Secondary, No-fault Insurance including Auto is Primary")]
        MedicareSecondaryNofaultInsuranceincludingAutoisPrimary,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Secondary Workers Compensation")]
        MedicareSecondaryWorkersCompensation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Secondary Public Health Service (PHS)or Other Federal Agency")]
        MedicareSecondaryPublicHealthServicePHSorOtherFederalAgency,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Secondary Black Lung")]
        MedicareSecondaryBlackLung,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Secondary Veterans Administration")]
        MedicareSecondaryVeteransAdministration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Secondary Disabled Beneficiary Under Age 65 with Large Group Health Plan" +
            " (LGHP)")]
        MedicareSecondaryDisabledBeneficiaryUnderAge65withLargeGroupHealthPlanLGHP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("47")]
        Item47,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Secondary, Other Liability Insurance is Primary")]
        MedicareSecondaryOtherLiabilityInsuranceisPrimary,
        
        /// <remarks/>
        AP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Auto Insurance Policy")]
        AutoInsurancePolicy,
        
        /// <remarks/>
        C1,
        
        /// <remarks/>
        Commercial,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Consolidated Omnibus Budget Reconciliation Act (COBRA)")]
        ConsolidatedOmnibusBudgetReconciliationActCOBRA,
        
        /// <remarks/>
        CP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Conditionally Primary")]
        MedicareConditionallyPrimary,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        Disability,
        
        /// <remarks/>
        DB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Disability Benefits")]
        DisabilityBenefits,
        
        /// <remarks/>
        EP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Exclusive Provider Organization")]
        ExclusiveProviderOrganization,
        
        /// <remarks/>
        FF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Family or Friends")]
        FamilyorFriends,
        
        /// <remarks/>
        GP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Group Policy")]
        GroupPolicy,
        
        /// <remarks/>
        HM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Health Maintenance Organization (HMO)")]
        HealthMaintenanceOrganizationHMO,
        
        /// <remarks/>
        HN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Health Maintenance Organization (HMO) - Medicare Risk")]
        HealthMaintenanceOrganizationHMOMedicareRisk,
        
        /// <remarks/>
        HS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Special Low Income Medicare Beneficiary")]
        SpecialLowIncomeMedicareBeneficiary,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        Indemnity,
        
        /// <remarks/>
        IP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Individual Policy")]
        IndividualPolicy,
        
        /// <remarks/>
        LC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Long Term Care")]
        LongTermCare,
        
        /// <remarks/>
        LD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Long Term Policy")]
        LongTermPolicy,
        
        /// <remarks/>
        LI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Life Insurance")]
        LifeInsurance,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        Litigation,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Part A")]
        MedicarePartA,
        
        /// <remarks/>
        MB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Part B")]
        MedicarePartB,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        Medicaid,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medigap Part A")]
        MedigapPartA,
        
        /// <remarks/>
        MI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medigap Part B")]
        MedigapPartB,
        
        /// <remarks/>
        MP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medicare Primary")]
        MedicarePrimary,
        
        /// <remarks/>
        OT,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Property Insurance - Personal")]
        PropertyInsurancePersonal,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        Personal,
        
        /// <remarks/>
        PP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Personal Payment (Cash - No Insurance)")]
        PersonalPaymentCashNoInsurance,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Preferred Provider Organization (PPO)")]
        PreferredProviderOrganizationPPO,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Point of Service (POS)")]
        PointofServicePOS,
        
        /// <remarks/>
        QM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Qualified Medicare Beneficiary")]
        QualifiedMedicareBeneficiary,
        
        /// <remarks/>
        RP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Property Insurance - Real")]
        PropertyInsuranceReal,
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Supplemental Policy")]
        SupplementalPolicy,
        
        /// <remarks/>
        TF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tax Equity Fiscal Responsibility Act (TEFRA)")]
        TaxEquityFiscalResponsibilityActTEFRA,
        
        /// <remarks/>
        WC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Workers Compensation")]
        WorkersCompensation,
        
        /// <remarks/>
        WU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Wrap Up Policy")]
        WrapUpPolicy,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Allscripts:momst")]
    public enum SubscriberRelationship {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Family dependent")]
        Familydependent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Handicapped dependent")]
        Handicappeddependent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Injured plaintiff")]
        Injuredplaintiff,
        
        /// <remarks/>
        Self,
        
        /// <remarks/>
        Student,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Full-time student")]
        Fulltimestudent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Part-time student")]
        Parttimestudent,
    }
}
