// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>CREF.Model</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace CREF.Model {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=false)]
    public partial class DynamicRule {
        
        private List<NamedExpression> dynamicRuleNamedExpressionsField;
        
        private DynamicRuleDynamicRuleCriteria dynamicRuleCriteriaField;
        
        private DynamicRuleDynamicRuleAssertion dynamicRuleAssertionField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string severityIDField;
        
        public DynamicRule() {
            this.dynamicRuleAssertionField = new DynamicRuleDynamicRuleAssertion();
            this.dynamicRuleCriteriaField = new DynamicRuleDynamicRuleCriteria();
            this.dynamicRuleNamedExpressionsField = new List<NamedExpression>();
        }
        
        [System.Xml.Serialization.XmlArrayAttribute("DynamicRule.NamedExpressions", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public List<NamedExpression> DynamicRuleNamedExpressions {
            get {
                return this.dynamicRuleNamedExpressionsField;
            }
            set {
                this.dynamicRuleNamedExpressionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DynamicRule.Criteria", Order=1)]
        public DynamicRuleDynamicRuleCriteria DynamicRuleCriteria {
            get {
                return this.dynamicRuleCriteriaField;
            }
            set {
                this.dynamicRuleCriteriaField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DynamicRule.Assertion", Order=2)]
        public DynamicRuleDynamicRuleAssertion DynamicRuleAssertion {
            get {
                return this.dynamicRuleAssertionField;
            }
            set {
                this.dynamicRuleAssertionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SeverityID {
            get {
                return this.severityIDField;
            }
            set {
                this.severityIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class NamedExpression {
        
        private object itemField;
        
        private string nameField;
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class BinaryExpression {
        
        private List<object> itemsField;
        
        private BinaryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        public BinaryExpression() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BinaryOperator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class CalculateAge {
        
        private List<object> itemsField;
        
        public CalculateAge() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class Choice {
        
        private List<object> itemsField;
        
        public Choice() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class Coalesce {
        
        private List<object> itemsField;
        
        public Coalesce() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class Code {
        
        private string codeValueField;
        
        private string codeDescriptionField;
        
        private string codeTypeField;
        
        private string codingSystemField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodeValue {
            get {
                return this.codeValueField;
            }
            set {
                this.codeValueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodeDescription {
            get {
                return this.codeDescriptionField;
            }
            set {
                this.codeDescriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodeType {
            get {
                return this.codeTypeField;
            }
            set {
                this.codeTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodingSystem {
            get {
                return this.codingSystemField;
            }
            set {
                this.codingSystemField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class ValueSetExpression {
        
        private string valueSetIDField;
        
        private int versionField;
        
        private bool versionFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueSetID {
            get {
                return this.valueSetIDField;
            }
            set {
                this.valueSetIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class ValueExpression {
        
        private ValueType typeField;
        
        private bool typeFieldSpecified;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    public enum ValueType {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Double,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class UnionExpression {
        
        private List<object> itemsField;
        
        private DateGranularity granularityField;
        
        private bool granularityFieldSpecified;
        
        public UnionExpression() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DateGranularity Granularity {
            get {
                return this.granularityField;
            }
            set {
                this.granularityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GranularitySpecified {
            get {
                return this.granularityFieldSpecified;
            }
            set {
                this.granularityFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class Condition {
        
        private List<object> itemsField;
        
        public Condition() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class DateAdd {
        
        private List<object> itemsField;
        
        private DateGranularity granularityField;
        
        private bool granularityFieldSpecified;
        
        private int numberOfPeriodsField;
        
        private bool numberOfPeriodsFieldSpecified;
        
        public DateAdd() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DateGranularity Granularity {
            get {
                return this.granularityField;
            }
            set {
                this.granularityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GranularitySpecified {
            get {
                return this.granularityFieldSpecified;
            }
            set {
                this.granularityFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumberOfPeriods {
            get {
                return this.numberOfPeriodsField;
            }
            set {
                this.numberOfPeriodsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfPeriodsSpecified {
            get {
                return this.numberOfPeriodsFieldSpecified;
            }
            set {
                this.numberOfPeriodsFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class DateDiff {
        
        private List<object> itemsField;
        
        private DateGranularity granularityField;
        
        private bool granularityFieldSpecified;
        
        public DateDiff() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DateGranularity Granularity {
            get {
                return this.granularityField;
            }
            set {
                this.granularityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GranularitySpecified {
            get {
                return this.granularityFieldSpecified;
            }
            set {
                this.granularityFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class DatePart {
        
        private object itemField;
        
        private DateGranularity granularityField;
        
        private bool granularityFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DateGranularity Granularity {
            get {
                return this.granularityField;
            }
            set {
                this.granularityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GranularitySpecified {
            get {
                return this.granularityFieldSpecified;
            }
            set {
                this.granularityFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class DateRange {
        
        private List<object> itemsField;
        
        public DateRange() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class DateRangeWithin {
        
        private List<object> itemsField;
        
        private DateGranularity granularityField;
        
        private bool granularityFieldSpecified;
        
        private int numberOfPeriodsField;
        
        private bool numberOfPeriodsFieldSpecified;
        
        public DateRangeWithin() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DateGranularity Granularity {
            get {
                return this.granularityField;
            }
            set {
                this.granularityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GranularitySpecified {
            get {
                return this.granularityFieldSpecified;
            }
            set {
                this.granularityFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumberOfPeriods {
            get {
                return this.numberOfPeriodsField;
            }
            set {
                this.numberOfPeriodsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfPeriodsSpecified {
            get {
                return this.numberOfPeriodsFieldSpecified;
            }
            set {
                this.numberOfPeriodsFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class ExpressionReference {
        
        private string nameField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class FilterExpression {
        
        private List<object> itemsField;
        
        public FilterExpression() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class IndexerExpression {
        
        private object itemField;
        
        private int indexField;
        
        private bool indexFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexSpecified {
            get {
                return this.indexFieldSpecified;
            }
            set {
                this.indexFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class ListExpression {
        
        private List<object> itemsField;
        
        public ListExpression() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class LogicalConnective {
        
        private List<object> itemsField;
        
        private LogicalConnectiveOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        public LogicalConnective() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LogicalConnectiveOperator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class ParameterExpression {
        
        private string nameField;
        
        private string defaultValueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class PropertyExpression {
        
        private object itemField;
        
        private string pathField;
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class RequestExpression {
        
        private List<object> itemsField;
        
        private List<CodedValueType> requestExpressionCodesField;
        
        private DateRange1 requestExpressionDateRangeField;
        
        private RequestCardinality cardinalityField;
        
        private bool cardinalityFieldSpecified;
        
        private PatientQueryType typeField;
        
        private bool typeFieldSpecified;
        
        public RequestExpression() {
            this.requestExpressionCodesField = new List<CodedValueType>();
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute("RequestExpression.Codes", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(CodedValueType), Namespace="urn:Allscripts:mombt", IsNullable=false)]
        public List<CodedValueType> RequestExpressionCodes {
            get {
                return this.requestExpressionCodesField;
            }
            set {
                this.requestExpressionCodesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression.DateRange", Order=2)]
        public DateRange1 RequestExpressionDateRange {
            get {
                return this.requestExpressionDateRangeField;
            }
            set {
                this.requestExpressionDateRangeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RequestCardinality Cardinality {
            get {
                return this.cardinalityField;
            }
            set {
                this.cardinalityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CardinalitySpecified {
            get {
                return this.cardinalityFieldSpecified;
            }
            set {
                this.cardinalityFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PatientQueryType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class SortExpression {
        
        private object itemField;
        
        private string orderByField;
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class Today {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class UnaryExpression {
        
        private object itemField;
        
        private UnaryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnaryOperator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    public enum UnaryOperator {
        
        /// <remarks/>
        opNot,
        
        /// <remarks/>
        opNegate,
        
        /// <remarks/>
        opExists,
        
        /// <remarks/>
        opFirst,
        
        /// <remarks/>
        opLast,
        
        /// <remarks/>
        opCount,
        
        /// <remarks/>
        opDayOfWeek,
        
        /// <remarks/>
        opDayOfYear,
        
        /// <remarks/>
        opFloor,
        
        /// <remarks/>
        opCeiling,
        
        /// <remarks/>
        opRound,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    public enum RequestCardinality {
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        Multiple,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    public enum LogicalConnectiveOperator {
        
        /// <remarks/>
        opAnd,
        
        /// <remarks/>
        opOr,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    public enum DateGranularity {
        
        /// <remarks/>
        Year,
        
        /// <remarks/>
        Month,
        
        /// <remarks/>
        Week,
        
        /// <remarks/>
        Day,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    public enum BinaryOperator {
        
        /// <remarks/>
        opAnd,
        
        /// <remarks/>
        opOr,
        
        /// <remarks/>
        opXor,
        
        /// <remarks/>
        opLess,
        
        /// <remarks/>
        opGreater,
        
        /// <remarks/>
        opLessOrEqual,
        
        /// <remarks/>
        opGreaterOrEqual,
        
        /// <remarks/>
        opEqual,
        
        /// <remarks/>
        opNotEqual,
        
        /// <remarks/>
        opAdd,
        
        /// <remarks/>
        opSubtract,
        
        /// <remarks/>
        opMultiply,
        
        /// <remarks/>
        opDivide,
        
        /// <remarks/>
        opPower,
        
        /// <remarks/>
        opMod,
        
        /// <remarks/>
        opDiv,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.allscripts.com/cds/evaluation")]
    public partial class DynamicRuleDynamicRuleCriteria {
        
        private object itemField;
        
        [System.Xml.Serialization.XmlElementAttribute("BinaryExpression", typeof(BinaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CalculateAge", typeof(CalculateAge), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Choice", typeof(Choice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Coalesce", typeof(Coalesce), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(Code), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Condition", typeof(Condition), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateAdd", typeof(DateAdd), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateDiff", typeof(DateDiff), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DatePart", typeof(DatePart), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRange", typeof(DateRange), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateRangeWithin", typeof(DateRangeWithin), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExpressionReference", typeof(ExpressionReference), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FilterExpression", typeof(FilterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndexerExpression", typeof(IndexerExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ListExpression", typeof(ListExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalConnective", typeof(LogicalConnective), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterExpression", typeof(ParameterExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyExpression", typeof(PropertyExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestExpression", typeof(RequestExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SortExpression", typeof(SortExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Today", typeof(Today), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnaryExpression", typeof(UnaryExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UnionExpression", typeof(UnionExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueExpression", typeof(ValueExpression), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ValueSetExpression", typeof(ValueSetExpression), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.allscripts.com/cds/evaluation")]
    public partial class DynamicRuleDynamicRuleAssertion {
        
        private ClinicalAssertion itemField;
        
        [System.Xml.Serialization.XmlElementAttribute("ClinicalAssertion", typeof(ClinicalAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CompositeAssertion", typeof(CompositeAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MissingDataAssertion", typeof(MissingDataAssertion), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OutOfRangeAssertion", typeof(OutOfRangeAssertion), Order=0)]
        public ClinicalAssertion Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.allscripts.com/cds/evaluation", IsNullable=true)]
    public partial class NamedExpressions {
        
        private List<NamedExpression> namedExpressionField;
        
        public NamedExpressions() {
            this.namedExpressionField = new List<NamedExpression>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("NamedExpression", Order=0)]
        public List<NamedExpression> NamedExpression {
            get {
                return this.namedExpressionField;
            }
            set {
                this.namedExpressionField = value;
            }
        }
    }
}
