// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>HeD.Model</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HeD.Model {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class AD : ANY {
        
        private List<ADXP> partField;
        
        private List<PostalAddressUse> useField;
        
        public AD() {
            this.useField = new List<PostalAddressUse>();
            this.partField = new List<ADXP>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("part", Order=0)]
        public List<ADXP> part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public List<PostalAddressUse> use {
            get {
                return this.useField;
            }
            set {
                this.useField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class ADXP : XP {
        
        private AddressPartType typeField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AddressPartType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    public enum AddressPartType {
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        ADL,
        
        /// <remarks/>
        UNID,
        
        /// <remarks/>
        UNIT,
        
        /// <remarks/>
        DAL,
        
        /// <remarks/>
        DINST,
        
        /// <remarks/>
        DINSTA,
        
        /// <remarks/>
        DINSTQ,
        
        /// <remarks/>
        DMOD,
        
        /// <remarks/>
        DMODID,
        
        /// <remarks/>
        SAL,
        
        /// <remarks/>
        BNR,
        
        /// <remarks/>
        BNN,
        
        /// <remarks/>
        BNS,
        
        /// <remarks/>
        STR,
        
        /// <remarks/>
        STB,
        
        /// <remarks/>
        STTYP,
        
        /// <remarks/>
        DIR,
        
        /// <remarks/>
        INT,
        
        /// <remarks/>
        CAR,
        
        /// <remarks/>
        CEN,
        
        /// <remarks/>
        CNT,
        
        /// <remarks/>
        CPA,
        
        /// <remarks/>
        CTY,
        
        /// <remarks/>
        DEL,
        
        /// <remarks/>
        POB,
        
        /// <remarks/>
        PRE,
        
        /// <remarks/>
        STA,
        
        /// <remarks/>
        ZIP,
        
        /// <remarks/>
        DPID,
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ENXP))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ADXP))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class XP {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ANY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AD))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QTY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(REAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PQ))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PIVL_TS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(INT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QSET))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_REAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_QTY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_PQ))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_INT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_TS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_CO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(II))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TEL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ED))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ST))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CD))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BL))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public abstract partial class HXIT {
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AD))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QTY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(REAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PQ))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PIVL_TS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(INT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QSET))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_REAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_QTY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_PQ))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_INT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_TS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_CO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(II))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TEL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ED))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ST))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CD))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BL))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public abstract partial class ANY : HXIT {
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(REAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PQ))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PIVL_TS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(INT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public abstract partial class QTY : ANY {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class REAL : QTY {
        
        private double valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class RTO : QTY {
        
        private QTY numeratorField;
        
        private QTY denominatorField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public QTY numerator {
            get {
                return this.numeratorField;
            }
            set {
                this.numeratorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public QTY denominator {
            get {
                return this.denominatorField;
            }
            set {
                this.denominatorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class PQ : QTY {
        
        private double valueField;
        
        private string unitField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class TS : QTY {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class PIVL_TS : QTY {
        
        private IVL_TS phaseField;
        
        private PQ periodField;
        
        private RTO frequencyField;
        
        private INT countField;
        
        private CalendarCycle alignmentField;
        
        private bool alignmentFieldSpecified;
        
        private bool isFlexibleField;
        
        private bool isFlexibleFieldSpecified;
        
        public PIVL_TS() {
            this.countField = new INT();
            this.frequencyField = new RTO();
            this.periodField = new PQ();
            this.phaseField = new IVL_TS();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IVL_TS phase {
            get {
                return this.phaseField;
            }
            set {
                this.phaseField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PQ period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RTO frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public INT count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CalendarCycle alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool alignmentSpecified {
            get {
                return this.alignmentFieldSpecified;
            }
            set {
                this.alignmentFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isFlexible {
            get {
                return this.isFlexibleField;
            }
            set {
                this.isFlexibleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isFlexibleSpecified {
            get {
                return this.isFlexibleFieldSpecified;
            }
            set {
                this.isFlexibleFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class IVL_TS : IVL {
        
        private TS lowField;
        
        private TS highField;
        
        private bool lowClosedField;
        
        private bool lowClosedFieldSpecified;
        
        private bool highClosedField;
        
        private bool highClosedFieldSpecified;
        
        public IVL_TS() {
            this.highField = new TS();
            this.lowField = new TS();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TS low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TS high {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool lowClosed {
            get {
                return this.lowClosedField;
            }
            set {
                this.lowClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lowClosedSpecified {
            get {
                return this.lowClosedFieldSpecified;
            }
            set {
                this.lowClosedFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool highClosed {
            get {
                return this.highClosedField;
            }
            set {
                this.highClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool highClosedSpecified {
            get {
                return this.highClosedFieldSpecified;
            }
            set {
                this.highClosedFieldSpecified = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_REAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_QTY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_PQ))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_INT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_TS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_CO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class IVL : QSET {
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_REAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_QTY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_PQ))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_INT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_TS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IVL_CO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public abstract partial class QSET : ANY {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class IVL_REAL : IVL {
        
        private REAL lowField;
        
        private REAL highField;
        
        private bool lowClosedField;
        
        private bool lowClosedFieldSpecified;
        
        private bool highClosedField;
        
        private bool highClosedFieldSpecified;
        
        public IVL_REAL() {
            this.highField = new REAL();
            this.lowField = new REAL();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public REAL low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public REAL high {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool lowClosed {
            get {
                return this.lowClosedField;
            }
            set {
                this.lowClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lowClosedSpecified {
            get {
                return this.lowClosedFieldSpecified;
            }
            set {
                this.lowClosedFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool highClosed {
            get {
                return this.highClosedField;
            }
            set {
                this.highClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool highClosedSpecified {
            get {
                return this.highClosedFieldSpecified;
            }
            set {
                this.highClosedFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class IVL_QTY : IVL {
        
        private QTY lowField;
        
        private QTY highField;
        
        private bool lowClosedField;
        
        private bool lowClosedFieldSpecified;
        
        private bool highClosedField;
        
        private bool highClosedFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public QTY low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public QTY high {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool lowClosed {
            get {
                return this.lowClosedField;
            }
            set {
                this.lowClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lowClosedSpecified {
            get {
                return this.lowClosedFieldSpecified;
            }
            set {
                this.lowClosedFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool highClosed {
            get {
                return this.highClosedField;
            }
            set {
                this.highClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool highClosedSpecified {
            get {
                return this.highClosedFieldSpecified;
            }
            set {
                this.highClosedFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class IVL_PQ : IVL {
        
        private PQ lowField;
        
        private PQ highField;
        
        private bool lowClosedField;
        
        private bool lowClosedFieldSpecified;
        
        private bool highClosedField;
        
        private bool highClosedFieldSpecified;
        
        public IVL_PQ() {
            this.highField = new PQ();
            this.lowField = new PQ();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PQ low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PQ high {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool lowClosed {
            get {
                return this.lowClosedField;
            }
            set {
                this.lowClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lowClosedSpecified {
            get {
                return this.lowClosedFieldSpecified;
            }
            set {
                this.lowClosedFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool highClosed {
            get {
                return this.highClosedField;
            }
            set {
                this.highClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool highClosedSpecified {
            get {
                return this.highClosedFieldSpecified;
            }
            set {
                this.highClosedFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class IVL_INT : IVL {
        
        private INT lowField;
        
        private INT highField;
        
        private bool lowClosedField;
        
        private bool lowClosedFieldSpecified;
        
        private bool highClosedField;
        
        private bool highClosedFieldSpecified;
        
        public IVL_INT() {
            this.highField = new INT();
            this.lowField = new INT();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public INT low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public INT high {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool lowClosed {
            get {
                return this.lowClosedField;
            }
            set {
                this.lowClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lowClosedSpecified {
            get {
                return this.lowClosedFieldSpecified;
            }
            set {
                this.lowClosedFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool highClosed {
            get {
                return this.highClosedField;
            }
            set {
                this.highClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool highClosedSpecified {
            get {
                return this.highClosedFieldSpecified;
            }
            set {
                this.highClosedFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class INT : QTY {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class IVL_CO : IVL {
        
        private CO lowField;
        
        private CO highField;
        
        private bool lowClosedField;
        
        private bool lowClosedFieldSpecified;
        
        private bool highClosedField;
        
        private bool highClosedFieldSpecified;
        
        public IVL_CO() {
            this.highField = new CO();
            this.lowField = new CO();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CO low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CO high {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool lowClosed {
            get {
                return this.lowClosedField;
            }
            set {
                this.lowClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lowClosedSpecified {
            get {
                return this.lowClosedFieldSpecified;
            }
            set {
                this.lowClosedFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool highClosed {
            get {
                return this.highClosedField;
            }
            set {
                this.highClosedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool highClosedSpecified {
            get {
                return this.highClosedFieldSpecified;
            }
            set {
                this.highClosedFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class CO : QTY {
        
        private CD codeField;
        
        private double valueField;
        
        private bool valueFieldSpecified;
        
        public CO() {
            this.codeField = new CD();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CD code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class CD : ANY {
        
        private ST displayNameField;
        
        private ST originalTextField;
        
        private List<CD> translationField;
        
        private string codeField;
        
        private string codeSystemField;
        
        private string codeSystemNameField;
        
        private string codeSystemVersionField;
        
        private string valueSetField;
        
        private string valueSetVersionField;
        
        public CD() {
            this.translationField = new List<CD>();
            this.originalTextField = new ST();
            this.displayNameField = new ST();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ST displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ST originalText {
            get {
                return this.originalTextField;
            }
            set {
                this.originalTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("translation", Order=2)]
        public List<CD> translation {
            get {
                return this.translationField;
            }
            set {
                this.translationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeSystem {
            get {
                return this.codeSystemField;
            }
            set {
                this.codeSystemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeSystemName {
            get {
                return this.codeSystemNameField;
            }
            set {
                this.codeSystemNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeSystemVersion {
            get {
                return this.codeSystemVersionField;
            }
            set {
                this.codeSystemVersionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueSet {
            get {
                return this.valueSetField;
            }
            set {
                this.valueSetField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueSetVersion {
            get {
                return this.valueSetVersionField;
            }
            set {
                this.valueSetVersionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class ST : ANY {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    public enum CalendarCycle {
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        MY,
        
        /// <remarks/>
        CM,
        
        /// <remarks/>
        CW,
        
        /// <remarks/>
        WM,
        
        /// <remarks/>
        WY,
        
        /// <remarks/>
        DM,
        
        /// <remarks/>
        CD,
        
        /// <remarks/>
        DY,
        
        /// <remarks/>
        DW,
        
        /// <remarks/>
        HD,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        NH,
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        SN,
        
        /// <remarks/>
        CS,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class II : ANY {
        
        private string rootField;
        
        private string extensionField;
        
        private string identifierNameField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string root {
            get {
                return this.rootField;
            }
            set {
                this.rootField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string identifierName {
            get {
                return this.identifierNameField;
            }
            set {
                this.identifierNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class EN : ANY {
        
        private List<ENXP> partField;
        
        private List<EntityNameUse> useField;
        
        public EN() {
            this.useField = new List<EntityNameUse>();
            this.partField = new List<ENXP>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("part", Order=0)]
        public List<ENXP> part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public List<EntityNameUse> use {
            get {
                return this.useField;
            }
            set {
                this.useField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class ENXP : XP {
        
        private EntityNamePartType typeField;
        
        private List<EntityNamePartQualifier> qualifierField;
        
        public ENXP() {
            this.qualifierField = new List<EntityNamePartQualifier>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EntityNamePartType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public List<EntityNamePartQualifier> qualifier {
            get {
                return this.qualifierField;
            }
            set {
                this.qualifierField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    public enum EntityNamePartType {
        
        /// <remarks/>
        FAM,
        
        /// <remarks/>
        GIV,
        
        /// <remarks/>
        TITLE,
        
        /// <remarks/>
        DEL,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    public enum EntityNamePartQualifier {
        
        /// <remarks/>
        LS,
        
        /// <remarks/>
        AC,
        
        /// <remarks/>
        NB,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        HON,
        
        /// <remarks/>
        BR,
        
        /// <remarks/>
        AD,
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        MID,
        
        /// <remarks/>
        CL,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        PFX,
        
        /// <remarks/>
        SFX,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    public enum EntityNameUse {
        
        /// <remarks/>
        ABC,
        
        /// <remarks/>
        IDE,
        
        /// <remarks/>
        SYL,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        OR,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        ANON,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        OLD,
        
        /// <remarks/>
        DN,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        PHON,
        
        /// <remarks/>
        SRCH,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class TEL : ANY {
        
        private string valueField;
        
        private List<TelecommunicationAddressUse> useField;
        
        private List<TelecommunicationCapability> capabilitiesField;
        
        public TEL() {
            this.capabilitiesField = new List<TelecommunicationCapability>();
            this.useField = new List<TelecommunicationAddressUse>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public List<TelecommunicationAddressUse> use {
            get {
                return this.useField;
            }
            set {
                this.useField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public List<TelecommunicationCapability> capabilities {
            get {
                return this.capabilitiesField;
            }
            set {
                this.capabilitiesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    public enum TelecommunicationAddressUse {
        
        /// <remarks/>
        H,
        
        /// <remarks/>
        HP,
        
        /// <remarks/>
        HV,
        
        /// <remarks/>
        WP,
        
        /// <remarks/>
        DIR,
        
        /// <remarks/>
        PUB,
        
        /// <remarks/>
        BAD,
        
        /// <remarks/>
        TMP,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        EC,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        PG,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    public enum TelecommunicationCapability {
        
        /// <remarks/>
        voice,
        
        /// <remarks/>
        fax,
        
        /// <remarks/>
        data,
        
        /// <remarks/>
        tty,
        
        /// <remarks/>
        sms,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class ED : ANY {
        
        private byte[] dataField;
        
        private object xmlField;
        
        private TEL referenceField;
        
        private byte[] integrityCheckField;
        
        private ST descriptionField;
        
        private string valueField;
        
        private string mediaTypeField;
        
        private string charsetField;
        
        private string languageField;
        
        private Compression compressionField;
        
        private bool compressionFieldSpecified;
        
        private IntegrityCheckAlgorithm integrityCheckAlgorithmField;
        
        private bool integrityCheckAlgorithmFieldSpecified;
        
        public ED() {
            this.descriptionField = new ST();
            this.referenceField = new TEL();
            this.mediaTypeField = "text/plain";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TEL reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] integrityCheck {
            get {
                return this.integrityCheckField;
            }
            set {
                this.integrityCheckField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ST description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("text/plain")]
        public string mediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string charset {
            get {
                return this.charsetField;
            }
            set {
                this.charsetField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Compression compression {
            get {
                return this.compressionField;
            }
            set {
                this.compressionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compressionSpecified {
            get {
                return this.compressionFieldSpecified;
            }
            set {
                this.compressionFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public IntegrityCheckAlgorithm integrityCheckAlgorithm {
            get {
                return this.integrityCheckAlgorithmField;
            }
            set {
                this.integrityCheckAlgorithmField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool integrityCheckAlgorithmSpecified {
            get {
                return this.integrityCheckAlgorithmFieldSpecified;
            }
            set {
                this.integrityCheckAlgorithmFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    public enum Compression {
        
        /// <remarks/>
        DF,
        
        /// <remarks/>
        GZ,
        
        /// <remarks/>
        ZL,
        
        /// <remarks/>
        Z,
        
        /// <remarks/>
        BZ,
        
        /// <remarks/>
        Z7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    public enum IntegrityCheckAlgorithm {
        
        /// <remarks/>
        SHA1,
        
        /// <remarks/>
        SHA256,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class CS : ANY {
        
        private string codeField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:cdsdt:r2", IsNullable=true)]
    public partial class BL : ANY {
        
        private bool valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:cdsdt:r2")]
    public enum PostalAddressUse {
        
        /// <remarks/>
        H,
        
        /// <remarks/>
        HP,
        
        /// <remarks/>
        HV,
        
        /// <remarks/>
        WP,
        
        /// <remarks/>
        DIR,
        
        /// <remarks/>
        PUB,
        
        /// <remarks/>
        BAD,
        
        /// <remarks/>
        PHYS,
        
        /// <remarks/>
        PST,
        
        /// <remarks/>
        TMP,
        
        /// <remarks/>
        ABC,
        
        /// <remarks/>
        IDE,
        
        /// <remarks/>
        SYL,
        
        /// <remarks/>
        SRCH,
        
        /// <remarks/>
        SNDX,
        
        /// <remarks/>
        PHON,
    }
}
