// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>HeD.Model</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace HeD.Model {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
	using CQL.ELM.Model;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    [System.Xml.Serialization.XmlRootAttribute("knowledgeDocument", Namespace="urn:hl7-org:knowledgeartifact:r1", IsNullable=false)]
    public partial class KnowledgeDocument {
        
        private Metadata metadataField;
        
        private KnowledgeDocumentExternalData externalDataField;
        
        private List<ExpressionDef> expressionsField;
        
        private List<Condition> conditionsField;
        
        private List<Behavior> behaviorsField;
        
        private ActionGroup actionGroupField;
        
        public KnowledgeDocument() {
            this.actionGroupField = new ActionGroup();
            this.behaviorsField = new List<Behavior>();
            this.conditionsField = new List<Condition>();
            this.expressionsField = new List<ExpressionDef>();
            this.externalDataField = new KnowledgeDocumentExternalData();
            this.metadataField = new Metadata();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Metadata metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public KnowledgeDocumentExternalData externalData {
            get {
                return this.externalDataField;
            }
            set {
                this.externalDataField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("def", IsNullable=false)]
        public List<ExpressionDef> expressions {
            get {
                return this.expressionsField;
            }
            set {
                this.expressionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("condition", IsNullable=false)]
        public List<Condition> conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("behavior", IsNullable=false)]
        public List<Behavior> behaviors {
            get {
                return this.behaviorsField;
            }
            set {
                this.behaviorsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ActionGroup actionGroup {
            get {
                return this.actionGroupField;
            }
            set {
                this.actionGroupField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class Metadata {
        
        private List<VersionedIdentifier> identifiersField;
        
        private MetadataArtifactType artifactTypeField;
        
        private VersionedIdentifier schemaIdentifierField;
        
        private List<VersionedIdentifier> templateIdsField;
        
        private List<ModelReference> dataModelsField;
        
        private List<LibraryReference> librariesField;
        
        private ST titleField;
        
        private ST descriptionField;
        
        private InlineResource documentationField;
        
        private List<ResourceRelationshipReference> relatedResourcesField;
        
        private List<Evidence> supportingEvidenceField;
        
        private List<Coverage> applicabilityField;
        
        private List<CD> keyTermsField;
        
        private List<CD> categoriesField;
        
        private CD languageField;
        
        private MetadataStatus statusField;
        
        private List<ArtifactLifeCycleEvent> eventHistoryField;
        
        private List<Contribution> contributionsField;
        
        private List<Party> publishersField;
        
        private List<RightsDeclaration> usageTermsField;
        
        public Metadata() {
            this.usageTermsField = new List<RightsDeclaration>();
            this.publishersField = new List<Party>();
            this.contributionsField = new List<Contribution>();
            this.eventHistoryField = new List<ArtifactLifeCycleEvent>();
            this.statusField = new MetadataStatus();
            this.languageField = new CD();
            this.categoriesField = new List<CD>();
            this.keyTermsField = new List<CD>();
            this.applicabilityField = new List<Coverage>();
            this.supportingEvidenceField = new List<Evidence>();
            this.relatedResourcesField = new List<ResourceRelationshipReference>();
            this.documentationField = new InlineResource();
            this.descriptionField = new ST();
            this.titleField = new ST();
            this.librariesField = new List<LibraryReference>();
            this.dataModelsField = new List<ModelReference>();
            this.templateIdsField = new List<VersionedIdentifier>();
            this.schemaIdentifierField = new VersionedIdentifier();
            this.artifactTypeField = new MetadataArtifactType();
            this.identifiersField = new List<VersionedIdentifier>();
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("identifier", IsNullable=false)]
        public List<VersionedIdentifier> identifiers {
            get {
                return this.identifiersField;
            }
            set {
                this.identifiersField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MetadataArtifactType artifactType {
            get {
                return this.artifactTypeField;
            }
            set {
                this.artifactTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public VersionedIdentifier schemaIdentifier {
            get {
                return this.schemaIdentifierField;
            }
            set {
                this.schemaIdentifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("templateId", IsNullable=false)]
        public List<VersionedIdentifier> templateIds {
            get {
                return this.templateIdsField;
            }
            set {
                this.templateIdsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("modelReference", IsNullable=false)]
        public List<ModelReference> dataModels {
            get {
                return this.dataModelsField;
            }
            set {
                this.dataModelsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("libraryReference", IsNullable=false)]
        public List<LibraryReference> libraries {
            get {
                return this.librariesField;
            }
            set {
                this.librariesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ST title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ST description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public InlineResource documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("relatedResource", IsNullable=false)]
        public List<ResourceRelationshipReference> relatedResources {
            get {
                return this.relatedResourcesField;
            }
            set {
                this.relatedResourcesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("evidence", IsNullable=false)]
        public List<Evidence> supportingEvidence {
            get {
                return this.supportingEvidenceField;
            }
            set {
                this.supportingEvidenceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("coverage", IsNullable=false)]
        public List<Coverage> applicability {
            get {
                return this.applicabilityField;
            }
            set {
                this.applicabilityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("term", IsNullable=false)]
        public List<CD> keyTerms {
            get {
                return this.keyTermsField;
            }
            set {
                this.keyTermsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("category", IsNullable=false)]
        public List<CD> categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public CD language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public MetadataStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute("artifactLifeCycleEvent", IsNullable=false)]
        public List<ArtifactLifeCycleEvent> eventHistory {
            get {
                return this.eventHistoryField;
            }
            set {
                this.eventHistoryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contribution", IsNullable=false)]
        public List<Contribution> contributions {
            get {
                return this.contributionsField;
            }
            set {
                this.contributionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("publisher", IsNullable=false)]
        public List<Party> publishers {
            get {
                return this.publishersField;
            }
            set {
                this.publishersField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=19)]
        [System.Xml.Serialization.XmlArrayItemAttribute("rightsDeclaration", IsNullable=false)]
        public List<RightsDeclaration> usageTerms {
            get {
                return this.usageTermsField;
            }
            set {
                this.usageTermsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class VersionedIdentifier : II {
        
        private string versionField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeriodicEventTrigger))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataEventTrigger))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public abstract partial class Trigger {
        
        private ExpressionDef defField;
        
        public Trigger() {
            this.defField = new ExpressionDef();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExpressionDef def {
            get {
                return this.defField;
            }
            set {
                this.defField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class PeriodicEventTrigger : Trigger {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class DataEventTrigger : Trigger {
        
        private DataEventType triggerTypeField;
        
        private bool triggerTypeFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataEventType triggerType {
            get {
                return this.triggerTypeField;
            }
            set {
                this.triggerTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool triggerTypeSpecified {
            get {
                return this.triggerTypeFieldSpecified;
            }
            set {
                this.triggerTypeFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public enum DataEventType {
        
        /// <remarks/>
        DataElementAdded,
        
        /// <remarks/>
        DataElementModified,
        
        /// <remarks/>
        DataElementRemoved,
        
        /// <remarks/>
        DataElementAccessed,
        
        /// <remarks/>
        DataElementAccessEnded,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ResponseBinding {
        
        private string containerField;
        
        private string propertyField;
        
        public ResponseBinding() {
            this.containerField = "Responses";
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Responses")]
        public string container {
            get {
                return this.containerField;
            }
            set {
                this.containerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionRef))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AtomicAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CollectInformationAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeclareResponseAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoveAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionGroup))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public abstract partial class ActionBase {
        
        private II actionIdField;
        
        private FormattedText numberField;
        
        private List<Evidence> supportingEvidenceField;
        
        private List<KnowledgeResource> supportingResourcesField;
        
        private List<Actor> actorsField;
        
        private List<Behavior> behaviorsField;
        
        private List<Condition> conditionsField;
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        public ActionBase() {
            this.conditionsField = new List<Condition>();
            this.behaviorsField = new List<Behavior>();
            this.actorsField = new List<Actor>();
            this.supportingResourcesField = new List<KnowledgeResource>();
            this.supportingEvidenceField = new List<Evidence>();
            this.numberField = new FormattedText();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public II actionId {
            get {
                return this.actionIdField;
            }
            set {
                this.actionIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FormattedText number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("evidence", IsNullable=false)]
        public List<Evidence> supportingEvidence {
            get {
                return this.supportingEvidenceField;
            }
            set {
                this.supportingEvidenceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("resource", IsNullable=false)]
        public List<KnowledgeResource> supportingResources {
            get {
                return this.supportingResourcesField;
            }
            set {
                this.supportingResourcesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("actor", IsNullable=false)]
        public List<Actor> actors {
            get {
                return this.actorsField;
            }
            set {
                this.actorsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("behavior", IsNullable=false)]
        public List<Behavior> behaviors {
            get {
                return this.behaviorsField;
            }
            set {
                this.behaviorsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("condition", IsNullable=false)]
        public List<Condition> conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class FormattedText {
        
        private string labelField;
        
        private List<string> styleField;
        
        private string valueField;
        
        public FormattedText() {
            this.styleField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("style", Order=1)]
        public List<string> style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class Evidence {
        
        private CD qualityOfEvidenceField;
        
        private CD strengthOfRecommendationField;
        
        private List<KnowledgeResource> resourcesField;
        
        public Evidence() {
            this.resourcesField = new List<KnowledgeResource>();
            this.strengthOfRecommendationField = new CD();
            this.qualityOfEvidenceField = new CD();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CD qualityOfEvidence {
            get {
                return this.qualityOfEvidenceField;
            }
            set {
                this.qualityOfEvidenceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CD strengthOfRecommendation {
            get {
                return this.strengthOfRecommendationField;
            }
            set {
                this.strengthOfRecommendationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("resource", IsNullable=false)]
        public List<KnowledgeResource> resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InlineResource))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class KnowledgeResource {
        
        private KnowledgeResourceIdentifiers identifiersField;
        
        private KnowledgeResourceTemplateIds templateIdsField;
        
        private FormattedText titleField;
        
        private TEL locationField;
        
        private FormattedText descriptionField;
        
        private FormattedText citationField;
        
        public KnowledgeResource() {
            this.citationField = new FormattedText();
            this.descriptionField = new FormattedText();
            this.locationField = new TEL();
            this.titleField = new FormattedText();
            this.templateIdsField = new KnowledgeResourceTemplateIds();
            this.identifiersField = new KnowledgeResourceIdentifiers();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public KnowledgeResourceIdentifiers identifiers {
            get {
                return this.identifiersField;
            }
            set {
                this.identifiersField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public KnowledgeResourceTemplateIds templateIds {
            get {
                return this.templateIdsField;
            }
            set {
                this.templateIdsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FormattedText title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TEL location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public FormattedText description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public FormattedText citation {
            get {
                return this.citationField;
            }
            set {
                this.citationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class KnowledgeResourceIdentifiers {
        
        private VersionedIdentifier identifierField;
        
        public KnowledgeResourceIdentifiers() {
            this.identifierField = new VersionedIdentifier();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VersionedIdentifier identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class KnowledgeResourceTemplateIds {
        
        private II templateIdField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public II templateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class InlineResource : KnowledgeResource {
        
        private InlineResourceContent contentField;
        
        public InlineResource() {
            this.contentField = new InlineResourceContent();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InlineResourceContent content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class InlineResourceContent {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class Actor {
        
        private Party actorField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Party actor {
            get {
                return this.actorField;
            }
            set {
                this.actorField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Person))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public abstract partial class Party {
        
        private List<AD> addressesField;
        
        private List<TEL> contactsField;
        
        public Party() {
            this.contactsField = new List<TEL>();
            this.addressesField = new List<AD>();
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("address", IsNullable=false)]
        public List<AD> addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contact", IsNullable=false)]
        public List<TEL> contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class Person : Party {
        
        private EN nameField;
        
        private Organization affiliationField;
        
        public Person() {
            this.affiliationField = new Organization();
            this.nameField = new EN();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EN name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Organization affiliation {
            get {
                return this.affiliationField;
            }
            set {
                this.affiliationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class Organization : Party {
        
        private ST nameField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ST name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CardinalityBehavior))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrecheckBehavior))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequiredBehavior))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupOrganizationBehavior))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupSelectionBehavior))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public abstract partial class Behavior {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class CardinalityBehavior : Behavior {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class PrecheckBehavior : Behavior {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class RequiredBehavior : Behavior {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class GroupOrganizationBehavior : Behavior {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class GroupSelectionBehavior : Behavior {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class Condition {
        
        private Expression logicField;
        
        private ConditionConditionRole conditionRoleField;
        
        public Condition() {
            this.conditionRoleField = new ConditionConditionRole();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Expression logic {
            get {
                return this.logicField;
            }
            set {
                this.logicField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ConditionConditionRole conditionRole {
            get {
                return this.conditionRoleField;
            }
            set {
                this.conditionRoleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ConditionConditionRole {
        
        private ConditionRoleType valueField;
        
        private bool valueFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConditionRoleType value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public enum ConditionRoleType {
        
        /// <remarks/>
        ApplicableScenario,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ActionRef : ActionBase {
        
        private string referencedActionIdField;
        
        private string libraryNameField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string referencedActionId {
            get {
                return this.referencedActionIdField;
            }
            set {
                this.referencedActionIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string libraryName {
            get {
                return this.libraryNameField;
            }
            set {
                this.libraryNameField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CollectInformationAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeclareResponseAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoveAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateAction))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public abstract partial class AtomicAction : ActionBase {
        
        private ST textEquivalentField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ST textEquivalent {
            get {
                return this.textEquivalentField;
            }
            set {
                this.textEquivalentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class CollectInformationAction : AtomicAction {
        
        private DocumentationItem documentationConceptField;
        
        private Expression initialValueField;
        
        private ResponseBinding responseBindingField;
        
        public CollectInformationAction() {
            this.responseBindingField = new ResponseBinding();
            this.documentationConceptField = new DocumentationItem();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DocumentationItem documentationConcept {
            get {
                return this.documentationConceptField;
            }
            set {
                this.documentationConceptField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Expression initialValue {
            get {
                return this.initialValueField;
            }
            set {
                this.initialValueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ResponseBinding responseBinding {
            get {
                return this.responseBindingField;
            }
            set {
                this.responseBindingField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class DocumentationItem : ItemDefinition {
        
        private FormattedText promptField;
        
        private List<FormattedText> additionalInstructionsField;
        
        private FormattedText textAfterResponseField;
        
        private FormattedText descriptionField;
        
        private List<CD> itemCodesField;
        
        private DocumentationItemResponseDataType responseDataTypeField;
        
        private DocumentationItemResponseCardinality responseCardinalityField;
        
        private List<RangeConstraint> responseRangeField;
        
        public DocumentationItem() {
            this.responseRangeField = new List<RangeConstraint>();
            this.responseCardinalityField = new DocumentationItemResponseCardinality();
            this.responseDataTypeField = new DocumentationItemResponseDataType();
            this.itemCodesField = new List<CD>();
            this.descriptionField = new FormattedText();
            this.textAfterResponseField = new FormattedText();
            this.additionalInstructionsField = new List<FormattedText>();
            this.promptField = new FormattedText();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FormattedText prompt {
            get {
                return this.promptField;
            }
            set {
                this.promptField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("additionalInstructions", Order=1)]
        public List<FormattedText> additionalInstructions {
            get {
                return this.additionalInstructionsField;
            }
            set {
                this.additionalInstructionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FormattedText textAfterResponse {
            get {
                return this.textAfterResponseField;
            }
            set {
                this.textAfterResponseField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public FormattedText description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemCode", IsNullable=false)]
        public List<CD> itemCodes {
            get {
                return this.itemCodesField;
            }
            set {
                this.itemCodesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public DocumentationItemResponseDataType responseDataType {
            get {
                return this.responseDataTypeField;
            }
            set {
                this.responseDataTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public DocumentationItemResponseCardinality responseCardinality {
            get {
                return this.responseCardinalityField;
            }
            set {
                this.responseCardinalityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("responseRange", Order=7)]
        public List<RangeConstraint> responseRange {
            get {
                return this.responseRangeField;
            }
            set {
                this.responseRangeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class DocumentationItemResponseDataType {
        
        private ValueType valueField;
        
        private bool valueFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueType value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public enum ValueType {
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        CodedOrdinal,
        
        /// <remarks/>
        EntityName,
        
        /// <remarks/>
        Identifier,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        IntegerInterval,
        
        /// <remarks/>
        Period,
        
        /// <remarks/>
        PhysicalQuantity,
        
        /// <remarks/>
        PhysicalQuantityInterval,
        
        /// <remarks/>
        QuantityInterval,
        
        /// <remarks/>
        Ratio,
        
        /// <remarks/>
        Real,
        
        /// <remarks/>
        RealInterval,
        
        /// <remarks/>
        SimpleCode,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Timestamp,
        
        /// <remarks/>
        TimestampInterval,
        
        /// <remarks/>
        URL,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class DocumentationItemResponseCardinality {
        
        private Cardinality valueField;
        
        private bool valueFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Cardinality value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public enum Cardinality {
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        Multiple,
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MaskConstraint))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueSetConstraint))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumerationConstraint))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LookupConstraint))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpressionConstraint))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public abstract partial class RangeConstraint {
        
        private RangeConstraintConstraintType constraintTypeField;
        
        public RangeConstraint() {
            this.constraintTypeField = new RangeConstraintConstraintType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RangeConstraintConstraintType constraintType {
            get {
                return this.constraintTypeField;
            }
            set {
                this.constraintTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class RangeConstraintConstraintType {
        
        private RangeConstraintType valueField;
        
        private bool valueFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RangeConstraintType value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public enum RangeConstraintType {
        
        /// <remarks/>
        Minimum,
        
        /// <remarks/>
        Maximum,
        
        /// <remarks/>
        List,
        
        /// <remarks/>
        Component,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class MaskConstraint : RangeConstraint {
        
        private ST maskExpressionField;
        
        private ST maskHelpField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ST maskExpression {
            get {
                return this.maskExpressionField;
            }
            set {
                this.maskExpressionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ST maskHelp {
            get {
                return this.maskHelpField;
            }
            set {
                this.maskHelpField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ValueSetConstraint : RangeConstraint {
        
        private ValueSetRef valueSetField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ValueSetRef valueSet {
            get {
                return this.valueSetField;
            }
            set {
                this.valueSetField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class EnumerationConstraint : RangeConstraint {
        
        private List<EnumerationItem> itemField;
        
        private bool strictSelectionField;
        
        private bool strictSelectionFieldSpecified;
        
        public EnumerationConstraint() {
            this.itemField = new List<EnumerationItem>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("item", Order=0)]
        public List<EnumerationItem> item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool strictSelection {
            get {
                return this.strictSelectionField;
            }
            set {
                this.strictSelectionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strictSelectionSpecified {
            get {
                return this.strictSelectionFieldSpecified;
            }
            set {
                this.strictSelectionFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class EnumerationItem {
        
        private VersionedIdentifier identifierField;
        
        private FormattedText numberField;
        
        private Expression valueField;
        
        private List<CD> codesField;
        
        private FormattedText displayTextField;
        
        private List<FormattedText> additionalInstructionsField;
        
        private FormattedText valueMeaningField;
        
        private bool fillInField;
        
        public EnumerationItem() {
            this.valueMeaningField = new FormattedText();
            this.additionalInstructionsField = new List<FormattedText>();
            this.displayTextField = new FormattedText();
            this.codesField = new List<CD>();
            this.numberField = new FormattedText();
            this.identifierField = new VersionedIdentifier();
            this.fillInField = false;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VersionedIdentifier identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FormattedText number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Expression value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("code", IsNullable=false)]
        public List<CD> codes {
            get {
                return this.codesField;
            }
            set {
                this.codesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public FormattedText displayText {
            get {
                return this.displayTextField;
            }
            set {
                this.displayTextField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("additionalInstructions", Order=5)]
        public List<FormattedText> additionalInstructions {
            get {
                return this.additionalInstructionsField;
            }
            set {
                this.additionalInstructionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public FormattedText valueMeaning {
            get {
                return this.valueMeaningField;
            }
            set {
                this.valueMeaningField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool fillIn {
            get {
                return this.fillInField;
            }
            set {
                this.fillInField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class LookupConstraint : RangeConstraint {
        
        private Expression itemsField;
        
        private string displayFieldField;
        
        private bool strictSelectionField;
        
        private bool strictSelectionFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Expression items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayField {
            get {
                return this.displayFieldField;
            }
            set {
                this.displayFieldField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool strictSelection {
            get {
                return this.strictSelectionField;
            }
            set {
                this.strictSelectionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strictSelectionSpecified {
            get {
                return this.strictSelectionFieldSpecified;
            }
            set {
                this.strictSelectionFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ExpressionConstraint : RangeConstraint {
        
        private Expression constraintField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Expression constraint {
            get {
                return this.constraintField;
            }
            set {
                this.constraintField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentationItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public abstract partial class ItemDefinition {
        
        private VersionedIdentifier identifierField;
        
        private VersionedIdentifier scopedIdentifierField;
        
        public ItemDefinition() {
            this.scopedIdentifierField = new VersionedIdentifier();
            this.identifierField = new VersionedIdentifier();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VersionedIdentifier identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VersionedIdentifier scopedIdentifier {
            get {
                return this.scopedIdentifierField;
            }
            set {
                this.scopedIdentifierField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class DeclareResponseAction : AtomicAction {
        
        private string nameField;
        
        public DeclareResponseAction() {
            this.nameField = "Responses";
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Responses")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class RemoveAction : AtomicAction {
        
        private Expression actionSentenceField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Expression actionSentence {
            get {
                return this.actionSentenceField;
            }
            set {
                this.actionSentenceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class UpdateAction : AtomicAction {
        
        private Expression actionSentenceField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Expression actionSentence {
            get {
                return this.actionSentenceField;
            }
            set {
                this.actionSentenceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class CreateAction : AtomicAction {
        
        private Expression actionSentenceField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Expression actionSentence {
            get {
                return this.actionSentenceField;
            }
            set {
                this.actionSentenceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ActionGroup : ActionBase {
        
        private FormattedText titleField;
        
        private FormattedText descriptionField;
        
        private List<CD> representedConceptsField;
        
        private ActionGroupSubElements subElementsField;
        
        public ActionGroup() {
            this.subElementsField = new ActionGroupSubElements();
            this.representedConceptsField = new List<CD>();
            this.descriptionField = new FormattedText();
            this.titleField = new FormattedText();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FormattedText title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FormattedText description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("concept", IsNullable=false)]
        public List<CD> representedConcepts {
            get {
                return this.representedConceptsField;
            }
            set {
                this.representedConceptsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ActionGroupSubElements subElements {
            get {
                return this.subElementsField;
            }
            set {
                this.subElementsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ActionGroupSubElements {
        
        private List<ActionBase> itemsField;
        
        public ActionGroupSubElements() {
            this.itemsField = new List<ActionBase>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("actionGroup", typeof(ActionGroup), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("actionRef", typeof(ActionRef), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("simpleAction", typeof(AtomicAction), Order=0)]
        public List<ActionBase> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class LibraryReference {
        
        private string nameField;
        
        private string mediaTypeField;
        
        private string pathField;
        
        private string versionField;
        
        public LibraryReference() {
            this.mediaTypeField = "application/hed+xml";
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        [System.ComponentModel.DefaultValueAttribute("application/hed+xml")]
        public string mediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ModelReference {
        
        private ST descriptionField;
        
        private ModelReferenceReferencedModel referencedModelField;
        
        public ModelReference() {
            this.referencedModelField = new ModelReferenceReferencedModel();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ST description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ModelReferenceReferencedModel referencedModel {
            get {
                return this.referencedModelField;
            }
            set {
                this.referencedModelField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ModelReferenceReferencedModel {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class RightsDeclaration {
        
        private ST assertedRightsField;
        
        private Party rightsHolderField;
        
        private List<ST> permissionsField;
        
        public RightsDeclaration() {
            this.permissionsField = new List<ST>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ST assertedRights {
            get {
                return this.assertedRightsField;
            }
            set {
                this.assertedRightsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Party rightsHolder {
            get {
                return this.rightsHolderField;
            }
            set {
                this.rightsHolderField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("permissions", IsNullable=false)]
        public List<ST> permissions {
            get {
                return this.permissionsField;
            }
            set {
                this.permissionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class Coverage {
        
        private CoverageFocus focusField;
        
        private ST descriptionField;
        
        private CD valueField;
        
        public Coverage() {
            this.focusField = new CoverageFocus();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CoverageFocus focus {
            get {
                return this.focusField;
            }
            set {
                this.focusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ST description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CD value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class CoverageFocus {
        
        private CoverageType valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CoverageType value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public enum CoverageType {
        
        /// <remarks/>
        PatientGender,
        
        /// <remarks/>
        PatientAgeGroup,
        
        /// <remarks/>
        ClinicalFocus,
        
        /// <remarks/>
        TargetUser,
        
        /// <remarks/>
        WorkflowSetting,
        
        /// <remarks/>
        WorkflowTask,
        
        /// <remarks/>
        ClinicalVenue,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class Contribution {
        
        private Party contributorField;
        
        private ContributionRole roleField;
        
        public Contribution() {
            this.roleField = new ContributionRole();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Party contributor {
            get {
                return this.contributorField;
            }
            set {
                this.contributorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ContributionRole role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ContributionRole {
        
        private ContributorType valueField;
        
        private bool valueFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ContributorType value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public enum ContributorType {
        
        /// <remarks/>
        Author,
        
        /// <remarks/>
        Editor,
        
        /// <remarks/>
        Endorser,
        
        /// <remarks/>
        Reviewer,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ArtifactLifeCycleEvent {
        
        private ArtifactLifeCycleEventEventType eventTypeField;
        
        private TS eventDateTimeField;
        
        public ArtifactLifeCycleEvent() {
            this.eventDateTimeField = new TS();
            this.eventTypeField = new ArtifactLifeCycleEventEventType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ArtifactLifeCycleEventEventType eventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TS eventDateTime {
            get {
                return this.eventDateTimeField;
            }
            set {
                this.eventDateTimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ArtifactLifeCycleEventEventType {
        
        private ArtifactLifeCycleEventType valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ArtifactLifeCycleEventType value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public enum ArtifactLifeCycleEventType {
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pre-published")]
        Prepublished,
        
        /// <remarks/>
        Published,
        
        /// <remarks/>
        Reviewed,
        
        /// <remarks/>
        Withdrawn,
        
        /// <remarks/>
        Superseded,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class FormattedNumber {
        
        private int labelField;
        
        private bool labelFieldSpecified;
        
        private List<string> styleField;
        
        private int valueField;
        
        private bool valueFieldSpecified;
        
        public FormattedNumber() {
            this.styleField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool labelSpecified {
            get {
                return this.labelFieldSpecified;
            }
            set {
                this.labelFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("style", Order=1)]
        public List<string> style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ResourceRelationshipReference {
        
        private ResourceRelationshipReferenceRelationship relationshipField;
        
        private List<KnowledgeResource> resourcesField;
        
        public ResourceRelationshipReference() {
            this.resourcesField = new List<KnowledgeResource>();
            this.relationshipField = new ResourceRelationshipReferenceRelationship();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResourceRelationshipReferenceRelationship relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("resource", IsNullable=false)]
        public List<KnowledgeResource> resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class ResourceRelationshipReferenceRelationship {
        
        private ResourceRelationshipType valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ResourceRelationshipType value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public enum ResourceRelationshipType {
        
        /// <remarks/>
        AdaptedFrom,
        
        /// <remarks/>
        AssociatedResource,
        
        /// <remarks/>
        DependsOn,
        
        /// <remarks/>
        DerivedFrom,
        
        /// <remarks/>
        SimilarTo,
        
        /// <remarks/>
        VersionOf,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class MetadataArtifactType {
        
        private ArtifactType valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ArtifactType value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public enum ArtifactType {
        
        /// <remarks/>
        Rule,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Order Set")]
        OrderSet,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Documentation Template")]
        DocumentationTemplate,
        
        /// <remarks/>
        Library,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class MetadataStatus {
        
        private ArtifactStatusType valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ArtifactStatusType value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public enum ArtifactStatusType {
        
        /// <remarks/>
        Draft,
        
        /// <remarks/>
        InTest,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Inactive,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:hl7-org:knowledgeartifact:r1")]
    public partial class KnowledgeDocumentExternalData {
        
        private List<CodeSystemDef> codesystemField;
        
        private List<ValueSetDef> valuesetField;
        
        private List<ParameterDef> parameterField;
        
        private List<ExpressionDef> defField;
        
        private List<Trigger> triggerField;
        
        public KnowledgeDocumentExternalData() {
            this.triggerField = new List<Trigger>();
            this.defField = new List<ExpressionDef>();
            this.parameterField = new List<ParameterDef>();
            this.valuesetField = new List<ValueSetDef>();
            this.codesystemField = new List<CodeSystemDef>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("codesystem", Order=0)]
        public List<CodeSystemDef> codesystem {
            get {
                return this.codesystemField;
            }
            set {
                this.codesystemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("valueset", Order=1)]
        public List<ValueSetDef> valueset {
            get {
                return this.valuesetField;
            }
            set {
                this.valuesetField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("parameter", Order=2)]
        public List<ParameterDef> parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("def", Order=3)]
        public List<ExpressionDef> def {
            get {
                return this.defField;
            }
            set {
                this.defField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("trigger", Order=4)]
        public List<Trigger> trigger {
            get {
                return this.triggerField;
            }
            set {
                this.triggerField = value;
            }
        }
    }
}
